# EDA
* 각 데이터 시트별로 살펴보겠습니다.

## 모듈 로드

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import gc

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
pd.set_option('display.max_columns', 400)
# pd.set_option('display.max_rows', 400)

## 데이터 로드

In [4]:
path = './data/'

In [7]:
history = pd.read_csv(path + 'historical_transactions.csv')

In [14]:
sorted(history.city_id.value_counts(dropna=False).index)

[-1,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 28,
 29,
 30,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 41,
 42,
 44,
 46,
 47,
 48,
 49,
 51,
 52,
 53,
 54,
 56,
 57,
 58,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 71,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 96,
 97,
 98,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 122,
 123,
 124,
 125,
 126,
 128,
 129,
 130,
 131,
 133,
 135,
 136,
 137,
 138,
 139,
 140,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 153,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 193,
 194,
 195,
 197,
 198,
 199,
 200,
 201,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 242,
 244,
 245,
 246,
 247,
 248,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 318,
 319,
 320,
 321,
 322,
 323,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 347]

In [20]:
history[history.card_id == 'C_ID_00007093c1'].sort_values('purchase_date')

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
19095896,Y,C_ID_00007093c1,244,N,2,C,705,M_ID_69423b34e4,-12,0.037176,2017-02-14 14:00:43,3.0,2,33
19095775,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_a33355a1b7,-12,-0.467415,2017-02-14 15:47:45,3.0,2,33
19095845,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-12,-0.572600,2017-02-16 15:37:58,3.0,2,19
19095866,Y,C_ID_00007093c1,244,N,3,C,705,M_ID_a33355a1b7,-12,-0.331575,2017-02-20 12:19:01,3.0,2,33
19095808,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-11,-0.483944,2017-03-03 00:24:15,3.0,2,19
19095905,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-11,-0.572600,2017-03-06 18:50:42,3.0,2,19
19095780,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-11,-0.401298,2017-03-08 15:05:29,3.0,2,33
19095816,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-11,-0.656749,2017-03-08 16:12:35,3.0,2,19
19095833,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-11,-0.566590,2017-03-11 15:04:31,3.0,2,33
19095922,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-11,-0.677936,2017-03-11 15:10:15,3.0,2,33
19095885,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-11,-0.566590,2017-03-11 15:26:58,3.0,2,33
19095855,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-11,-0.557574,2017-03-11 16:28:46,3.0,2,19
19095882,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-11,-0.557574,2017-03-11 16:29:20,3.0,2,19
19095837,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-11,-0.671775,2017-03-15 17:13:38,3.0,2,19
19095900,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_bc3f2e986e,-10,-0.692061,2017-04-17 19:19:54,3.0,2,33
19095787,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_bc3f2e986e,-10,-0.668319,2017-04-17 19:22:18,3.0,2,33
19095910,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-10,-0.578611,2017-04-17 19:37:08,3.0,2,19
19095862,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-10,-0.728876,2017-04-17 20:20:37,NaN,-1,8
19095805,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-10,-0.728876,2017-04-17 20:29:12,NaN,-1,8
19095781,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-10,-0.656749,2017-04-17 21:31:17,3.0,2,19
19095891,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-10,0.004418,2017-04-19 11:46:58,3.0,2,33
19095841,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-10,-0.418654,2017-04-19 12:19:08,3.0,2,33
19095858,N,C_ID_00007093c1,244,N,1,B,705,M_ID_8261f7a734,-10,-0.311139,2017-04-19 12:34:46,3.0,2,33
19095873,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_8261f7a734,-10,-0.446378,2017-04-19 12:35:45,3.0,2,33
19095815,N,C_ID_00007093c1,244,N,1,B,705,M_ID_8261f7a734,-10,-0.611669,2017-04-19 12:36:29,3.0,2,33
19095884,N,C_ID_00007093c1,244,N,1,B,705,M_ID_8261f7a734,-10,-0.671775,2017-04-19 12:36:49,3.0,2,33
19095875,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-9,-0.596447,2017-05-11 18:56:46,3.0,2,19
19095898,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-9,-0.623690,2017-05-15 14:50:52,3.0,2,19
19095908,Y,C_ID_00007093c1,244,N,1,B,367,M_ID_109e9d2b1d,-9,-0.587627,2017-05-16 17:16:11,3.0,2,16
19095776,N,C_ID_00007093c1,244,N,1,B,108,M_ID_15446e939c,-9,0.307953,2017-05-18 16:52:22,3.0,2,34
19095794,N,C_ID_00007093c1,244,N,1,B,108,M_ID_15446e939c,-9,0.307953,2017-05-18 16:53:21,3.0,2,34
19095889,N,C_ID_00007093c1,244,N,1,B,108,M_ID_15446e939c,-9,0.004418,2017-05-18 16:53:49,3.0,2,34
19095907,Y,C_ID_00007093c1,244,N,1,B,108,M_ID_15446e939c,-9,-0.296112,2017-05-18 16:54:17,3.0,2,34
19095890,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-9,-0.698823,2017-05-22 16:12:35,3.0,2,19
19095872,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-9,-0.661257,2017-05-29 14:44:58,3.0,2,19
19095842,Y,C_ID_00007093c1,244,N,1,B,607,M_ID_3c6556f2dd,-9,-0.581616,2017-05-30 11:10:06,3.0,2,29
19095886,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-8,-0.565763,2017-06-01 18:42:38,3.0,2,33
19095916,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-8,-0.683766,2017-06-01 19:30:29,3.0,2,19
19095906,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-8,-0.626696,2017-06-06 21:01:12,3.0,2,19
19095871,Y,C_ID_00007093c1,244,N,1,B,45,M_ID_0379adb435,-8,-0.662759,2017-06-07 10:28:34,3.0,2,18
19095881,Y,C_ID_00007093c1,244,N,2,C,298,M_ID_0dabc5a70c,-8,-0.599648,2017-06-07 10:47:20,3.0,2,10
19095892,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-8,-0.452388,2017-06-07 17:15:05,3.0,2,19
19095851,Y,C_ID_00007093c1,244,N,3,C,427,M_ID_24e067cb2b,-8,-0.234504,2017-06-09 10:47:39,3.0,2,27
19095793,Y,C_ID_00007093c1,76,N,1,B,422,M_ID_a614b6d5b0,-8,-0.701828,2017-06-10 11:06:51,3.0,2,27
19095883,N,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-8,-0.728876,2017-06-14 14:18:48,NaN,-1,8
19095874,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-8,-0.721363,2017-06-14 14:22:05,NaN,-1,8
19095880,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-8,-0.673278,2017-06-14 18:14:15,3.0,2,19
19095783,N,C_ID_00007093c1,244,N,3,C,222,M_ID_ee8fcd02ca,-8,0.004418,2017-06-17 10:53:40,3.0,2,21
19095899,N,C_ID_00007093c1,244,N,3,C,222,M_ID_ee8fcd02ca,-8,-0.145847,2017-06-17 10:54:08,3.0,2,21
19095822,N,C_ID_00007093c1,244,N,3,C,222,M_ID_ee8fcd02ca,-8,-0.296112,2017-06-17 10:54:36,3.0,2,21
19095829,Y,C_ID_00007093c1,244,N,2,C,222,M_ID_ee8fcd02ca,-8,-0.446378,2017-06-17 10:55:05,3.0,2,21
19095788,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-8,-0.619182,2017-06-23 13:17:47,3.0,2,19
19095856,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_a33355a1b7,-8,-0.566590,2017-06-29 16:10:08,3.0,2,33
19095914,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-8,-0.574058,2017-06-29 16:52:18,3.0,2,19
19095854,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-8,-0.574058,2017-06-29 16:52:47,3.0,2,19
19095807,Y,C_ID_00007093c1,76,N,1,B,307,M_ID_f5668a871f,-7,-0.716855,2017-07-02 08:23:52,3.0,2,19
19095795,Y,C_ID_00007093c1,76,N,1,B,705,M_ID_d96a11b2df,-7,-0.576823,2017-07-02 09:01:40,3.0,2,33
19095778,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-7,-0.709342,2017-07-03 15:43:57,NaN,-1,8
19095895,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-7,-0.564185,2017-07-04 17:14:03,3.0,2,33
19095852,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_bc3f2e986e,-7,-0.392282,2017-07-04 17:33:17,3.0,2,33
19095799,Y,C_ID_00007093c1,244,N,1,B,367,M_ID_109e9d2b1d,-7,-0.688304,2017-07-05 17:27:26,3.0,2,16
19095796,Y,C_ID_00007093c1,76,N,1,B,683,M_ID_6a1f75f661,-7,-0.416325,2017-07-05 17:57:21,3.0,2,34
19095888,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-7,-0.721363,2017-07-06 10:58:03,NaN,-1,8
19095846,Y,C_ID_00007093c1,244,N,2,C,45,M_ID_0379adb435,-7,-0.520007,2017-07-06 12:41:24,3.0,2,18
19095836,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-7,-0.686802,2017-07-08 11:58:06,3.0,2,19
19095797,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-7,-0.721363,2017-07-14 11:51:05,NaN,-1,8
19095801,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-7,-0.610167,2017-07-18 13:48:46,3.0,2,19
19095894,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-7,-0.721363,2017-07-31 16:01:04,NaN,-1,8
19095869,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-7,-0.596643,2017-07-31 21:30:24,3.0,2,19
19095876,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-7,-0.596643,2017-07-31 21:31:36,3.0,2,19
19095912,N,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-6,-0.709342,2017-08-01 07:13:59,NaN,-1,8
19095839,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-6,-0.709342,2017-08-01 07:16:57,NaN,-1,8
19095819,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-6,-0.596643,2017-08-04 15:40:55,3.0,2,19
19095834,Y,C_ID_00007093c1,76,N,1,B,206,M_ID_584ad6cd63,-6,-0.055688,2017-08-05 10:23:37,3.0,2,1
19095777,Y,C_ID_00007093c1,76,N,3,C,45,M_ID_84e60960a3,-6,-0.559076,2017-08-05 11:27:35,3.0,2,18
19095897,Y,C_ID_00007093c1,76,N,1,B,705,M_ID_d96a11b2df,-6,-0.596643,2017-08-06 07:49:23,3.0,2,33
19095790,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-6,-0.721363,2017-08-07 17:46:13,NaN,-1,8
19095840,Y,C_ID_00007093c1,244,N,2,C,45,M_ID_0379adb435,-6,-0.649235,2017-08-08 15:26:32,3.0,2,18
19095838,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-6,-0.721363,2017-08-14 12:11:26,NaN,-1,8
19095830,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-6,-0.596643,2017-08-14 16:51:19,3.0,2,19
19095913,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-6,-0.557574,2017-08-18 14:09:09,3.0,2,19
19095826,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-6,-0.721363,2017-08-22 09:17:57,NaN,-1,8
19095893,Y,C_ID_00007093c1,76,N,1,B,683,M_ID_6a1f75f661,-6,-0.641722,2017-08-26 09:51:16,3.0,2,34
19095863,N,C_ID_00007093c1,244,N,3,C,373,M_ID_490fc654fb,-6,1.507069,2017-08-28 11:43:28,3.0,2,18
19095791,Y,C_ID_00007093c1,244,N,3,C,373,M_ID_490fc654fb,-6,1.206539,2017-08-28 11:44:16,3.0,2,18
19095847,N,C_ID_00007093c1,244,N,1,B,373,M_ID_490fc654fb,-6,-0.596643,2017-08-28 11:46:28,3.0,2,18
19095843,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-6,-0.683796,2017-08-28 19:21:16,3.0,2,19
19095809,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-5,-0.709342,2017-09-04 15:07:02,NaN,-1,8
19095887,N,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-5,-0.721363,2017-09-08 13:24:49,NaN,-1,8
19095818,Y,C_ID_00007093c1,244,N,3,C,45,M_ID_0379adb435,-5,-0.416325,2017-09-25 12:14:35,3.0,2,18
19095850,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-5,-0.577003,2017-09-25 20:07:44,3.0,2,19
19095911,Y,C_ID_00007093c1,244,N,3,C,298,M_ID_0dabc5a70c,-5,-0.522261,2017-09-28 14:39:39,3.0,2,10
19095810,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.709342,2017-10-01 08:05:54,NaN,-1,8
19095825,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.709342,2017-10-02 12:40:58,NaN,-1,8
19095803,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.721363,2017-10-02 15:37:23,NaN,-1,8
19095921,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_8261f7a734,-4,-0.586124,2017-10-02 17:41:36,3.0,2,33
19095774,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-4,-0.530526,2017-10-02 19:09:42,3.0,2,19
19095798,N,C_ID_00007093c1,244,N,2,C,45,M_ID_58fa2d2ab7,-4,-0.536537,2017-10-05 21:22:06,3.0,2,18
19095804,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-4,-0.649566,2017-10-05 21:55:06,3.0,2,19
19095919,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_5357547c3e,-4,-0.515500,2017-10-06 21:40:23,3.0,2,19
19095901,N,C_ID_00007093c1,244,N,1,B,705,M_ID_8261f7a734,-4,-0.517002,2017-10-09 15:53:29,3.0,2,33
19095878,N,C_ID_00007093c1,244,N,1,B,705,M_ID_8261f7a734,-4,-0.517002,2017-10-09 15:54:04,3.0,2,33
19095879,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.721363,2017-10-19 14:20:38,NaN,-1,8
19095824,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-4,-0.649205,2017-10-23 22:47:52,3.0,2,19
19095828,Y,C_ID_00007093c1,244,N,1,B,68,M_ID_61f1337e5d,-4,-0.664262,2017-10-26 21:04:26,3.0,2,27
19095867,Y,C_ID_00007093c1,244,N,1,B,126,M_ID_f6d28ce95b,-4,-0.626846,2017-10-26 21:19:15,3.0,2,27
19095817,N,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.671941,2017-10-28 16:13:10,NaN,-1,8
19095904,Y,C_ID_00007093c1,76,N,1,B,683,M_ID_6a1f75f661,-4,-0.523013,2017-10-28 19:42:29,3.0,2,34
19095849,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_5357547c3e,-4,-0.574103,2017-10-28 20:11:04,3.0,2,19
19095835,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-3,-0.709342,2017-11-01 07:05:09,NaN,-1,8
19095831,Y,C_ID_00007093c1,333,N,2,C,307,M_ID_1b440d74fb,-3,-0.392282,2017-11-03 19:24:09,5.0,21,19
19095813,Y,C_ID_00007093c1,76,N,6,C,45,M_ID_84e60960a3,-3,0.044989,2017-11-09 16:20:00,3.0,2,18
19095802,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-3,-0.721363,2017-11-10 15:34:30,NaN,-1,8
19095827,N,C_ID_00007093c1,76,N,1,B,705,M_ID_edeafa75d9,-3,-0.569219,2017-11-10 16:21:22,3.0,2,33
19095820,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-3,-0.721363,2017-11-20 17:27:59,NaN,-1,8
19095864,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-2,-0.709342,2017-12-01 05:06:36,NaN,-1,8
19095821,Y,C_ID_00007093c1,244,N,3,C,222,M_ID_ee8fcd02ca,-2,-0.416325,2017-12-01 11:02:37,3.0,2,21
19095789,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-2,-0.561916,2017-12-01 19:24:28,3.0,2,19
19095784,Y,C_ID_00007093c1,244,N,1,B,222,M_ID_ee8fcd02ca,-2,-0.296112,2017-12-04 18:03:51,3.0,2,21
19095868,Y,C_ID_00007093c1,244,N,1,B,222,M_ID_ee8fcd02ca,-2,-0.353213,2017-12-07 17:48:54,3.0,2,21
19095915,N,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-2,-0.145847,2017-12-09 11:34:09,3.0,2,33
19095814,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-2,-0.641677,2017-12-09 13:59:34,3.0,2,19
19095918,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-2,-0.701753,2017-12-13 20:07:17,3.0,2,19
19095909,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-2,-0.671775,2017-12-13 20:08:05,3.0,2,19
19095832,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-2,-0.553066,2017-12-28 18:25:55,3.0,2,19
19095902,Y,C_ID_00007093c1,244,N,3,C,45,M_ID_58fa2d2ab7,-2,-0.311139,2017-12-30 13:06:45,3.0,2,18
19095917,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-2,-0.617635,2017-12-30 16:29:38,3.0,2,19
19095857,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-1,-0.709342,2018-01-01 05:07:37,NaN,-1,8
19095779,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_5357547c3e,-1,-0.392282,2018-01-05 13:55:01,3.0,2,19
19095782,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_a33355a1b7,-1,-0.418443,2018-01-08 16:15:07,3.0,2,33
19095860,Y,C_ID_00007093c1,244,N,1,B,705,M_ID_69423b34e4,-1,-0.446378,2018-01-08 16:58:13,3.0,2,33
19095848,Y,C_ID_00007093c1,244,N,1,B,45,M_ID_2efbd71a00,-1,-0.668770,2018-01-08 18:13:40,3.0,2,18
19095920,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-1,-0.521510,2018-01-08 18:58:43,3.0,2,19
19095823,N,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-1,-0.596643,2018-01-08 18:59:09,3.0,2,19
19095853,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-1,-0.671775,2018-01-08 18:59:38,3.0,2,19
19095812,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,-1,-0.709342,2018-01-30 05:06:15,NaN,-1,8
19095806,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_9400cf2342,-1,-0.551563,2018-01-30 19:27:40,3.0,2,19
19095861,Y,C_ID_00007093c1,244,N,1,B,307,M_ID_5357547c3e,0,-0.530030,2018-02-02 18:28:53,3.0,2,19
19095785,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,0,-0.721363,2018-02-05 08:56:11,NaN,-1,8
19095844,Y,C_ID_00007093c1,76,N,5,C,45,M_ID_84e60960a3,0,0.004418,2018-02-06 15:34:09,3.0,2,18
19095865,Y,C_ID_00007093c1,76,N,1,B,818,M_ID_c6ca6282e6,0,-0.623690,2018-02-07 07:34:15,3.0,2,12
19095792,N,C_ID_00007093c1,76,N,2,C,206,M_ID_584ad6cd63,0,-0.501224,2018-02-07 09:50:43,3.0,2,1
19095800,Y,C_ID_00007093c1,76,N,2,C,206,M_ID_584ad6cd63,0,-0.501224,2018-02-07 09:51:03,3.0,2,1
19095811,Y,C_ID_00007093c1,76,N,2,C,206,M_ID_584ad6cd63,0,-0.501224,2018-02-07 09:54:23,3.0,2,1
19095859,Y,C_ID_00007093c1,76,N,1,B,437,M_ID_06a8d84366,0,-0.435198,2018-02-07 11:11:27,3.0,2,15
19095870,N,C_ID_00007093c1,76,N,1,B,705,M_ID_d96a11b2df,0,-0.463042,2018-02-08 16:35:37,3.0,2,33
19095903,N,C_ID_00007093c1,76,N,1,B,705,M_ID_d96a11b2df,0,-0.596643,2018-02-08 16:36:19,3.0,2,33
19095786,N,C_ID_00007093c1,76,N,1,B,705,M_ID_d96a11b2df,0,-0.671775,2018-02-08 16:37:19,3.0,2,33
19095877,Y,C_ID_00007093c1,-1,Y,1,B,755,M_ID_57df19bf28,0,-0.709342,2018-02-27 05:14:57,NaN,-1,8

In [24]:
history[history.category_1 == 'Y']

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
797,Y,C_ID_48fb13e70f,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.649837,2017-12-09 13:04:14,NaN,-1,29
800,Y,C_ID_48fb13e70f,-1,Y,1,B,839,M_ID_50076f761c,-5,-0.596793,2017-09-21 23:28:00,NaN,-1,29
802,Y,C_ID_48fb13e70f,-1,Y,4,C,302,M_ID_b9f9332438,-8,0.764910,2017-06-07 05:20:49,NaN,-1,22
845,N,C_ID_48fb13e70f,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.649837,2017-12-20 20:38:40,NaN,-1,29
853,Y,C_ID_48fb13e70f,-1,Y,2,C,637,M_ID_963ed874ee,-1,-0.085741,2018-01-21 22:14:21,NaN,-1,37
997,Y,C_ID_fc8e41b9cf,-1,Y,10,C,706,M_ID_23ddadf852,-1,0.786548,2018-01-23 16:15:49,NaN,-1,26
1362,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,-1,-0.671925,2017-12-20 13:25:23,NaN,-1,8
1388,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,0,-0.671925,2018-01-21 09:51:02,NaN,-1,8
1420,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,-4,-0.671925,2017-09-24 18:16:10,NaN,-1,8
1422,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,-2,-0.671925,2017-11-19 16:22:11,NaN,-1,8
1428,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,-3,-0.671925,2017-10-19 18:08:32,NaN,-1,8
1430,Y,C_ID_4bed29d75c,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.745405,2017-09-24 17:16:29,NaN,-1,8
1438,N,C_ID_4bed29d75c,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.745405,2017-09-24 17:15:59,NaN,-1,8
2327,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.732197,2017-11-30 20:35:47,NaN,-1,29
2338,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.737907,2017-11-29 00:56:26,NaN,-1,29
2372,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733023,2017-12-01 22:03:29,NaN,-1,29
2382,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733925,2017-12-01 13:16:07,NaN,-1,29
2385,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.737877,2017-12-06 00:59:28,NaN,-1,29
2388,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,-4,-0.680791,2017-10-05 00:22:36,NaN,-1,29
2396,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.709176,2018-02-03 11:35:17,NaN,-1,29
2398,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.738268,2017-12-08 07:09:21,NaN,-1,29
2413,N,C_ID_058b254a5b,-1,Y,4,C,879,M_ID_9139332ccc,-7,-0.521660,2017-07-27 21:09:03,NaN,-1,29
2424,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733865,2017-12-11 07:04:43,NaN,-1,29
2444,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.729913,2017-12-01 21:23:42,NaN,-1,29
2448,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,-4,-0.679288,2017-10-25 01:26:07,NaN,-1,29
2454,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-04 14:54:14,NaN,-1,29
2483,Y,C_ID_058b254a5b,-1,Y,5,C,879,M_ID_9139332ccc,-3,-0.542187,2017-11-20 16:45:49,NaN,-1,29
2487,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,0,-0.685299,2018-02-09 22:48:36,NaN,-1,29
2491,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-04 14:54:56,NaN,-1,29
2493,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.738087,2017-12-02 21:39:00,NaN,-1,29
2503,N,C_ID_058b254a5b,-1,Y,10,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:26:26,NaN,-1,29
2511,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.710619,2017-12-01 21:48:05,NaN,-1,29
2520,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.710619,2017-12-04 12:40:44,NaN,-1,29
2521,N,C_ID_058b254a5b,-1,Y,4,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:24:40,NaN,-1,29
2522,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.692211,2017-11-26 03:14:09,NaN,-1,29
2524,Y,C_ID_058b254a5b,-1,Y,5,C,879,M_ID_9139332ccc,-3,-0.501405,2017-11-12 17:55:24,NaN,-1,29
2536,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.726457,2017-12-11 08:02:40,NaN,-1,29
2560,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.735037,2017-12-05 18:29:33,NaN,-1,29
2565,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.738268,2017-11-28 23:12:46,NaN,-1,29
2570,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733669,2017-12-08 18:58:08,NaN,-1,29
2571,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733730,2017-12-05 21:47:29,NaN,-1,29
2572,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.738268,2017-11-29 01:09:51,NaN,-1,29
2585,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.731731,2017-12-14 23:41:26,NaN,-1,29
2598,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,-4,-0.719860,2017-10-25 01:29:13,NaN,-1,29
2618,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-23 09:36:39,NaN,-1,29
2621,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.735999,2017-11-26 02:32:09,NaN,-1,29
2636,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.737276,2017-12-06 11:23:01,NaN,-1,29
2644,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.739274,2017-11-27 00:02:44,NaN,-1,29
2649,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-03 18:11:21,NaN,-1,29
2650,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-28 14:44:32,NaN,-1,29
2652,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.738087,2017-12-03 19:22:06,NaN,-1,29
2655,N,C_ID_058b254a5b,-1,Y,12,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:27:02,NaN,-1,29
2661,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.667478,2018-01-23 09:38:35,NaN,-1,29
2662,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.667463,2018-01-23 09:41:34,NaN,-1,29
2677,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.727779,2017-12-02 22:03:14,NaN,-1,29
2699,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.740897,2017-11-26 02:31:49,NaN,-1,29
2702,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733008,2017-12-11 07:03:20,NaN,-1,29
2703,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.717426,2018-01-28 14:49:07,NaN,-1,29
2706,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.738268,2017-12-08 07:18:51,NaN,-1,29
2714,Y,C_ID_058b254a5b,-1,Y,4,C,879,M_ID_9139332ccc,-7,-0.242017,2017-07-16 21:46:22,NaN,-1,29
2717,Y,C_ID_058b254a5b,-1,Y,2,C,879,M_ID_9139332ccc,-2,-0.690108,2017-12-07 23:43:18,NaN,-1,29
2722,N,C_ID_058b254a5b,-1,Y,10,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:26:15,NaN,-1,29
2734,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733669,2017-12-08 19:27:00,NaN,-1,29
2749,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-28 14:47:39,NaN,-1,29
2750,N,C_ID_058b254a5b,-1,Y,6,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:25:33,NaN,-1,29
2762,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.736585,2017-12-02 21:42:53,NaN,-1,29
2765,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.737817,2017-11-27 19:55:00,NaN,-1,29
2769,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.726517,2018-02-14 05:19:57,NaN,-1,29
2779,Y,C_ID_058b254a5b,-1,Y,2,C,879,M_ID_9139332ccc,0,-0.401148,2018-02-16 12:30:30,NaN,-1,29
2794,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,0,-0.684923,2018-02-09 22:46:41,NaN,-1,29
2830,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-01 13:33:34,NaN,-1,22
2847,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-2,-0.733399,2017-06-27 13:12:23,NaN,-1,22
2853,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.501991,2017-08-22 10:12:57,NaN,-1,22
2855,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-1,-0.733399,2017-07-18 13:16:42,NaN,-1,22
2861,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-5,-0.716735,2017-03-27 20:13:44,NaN,-1,22
2885,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-15 13:14:54,NaN,-1,22
2914,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-5,-0.742400,2017-03-27 20:10:19,NaN,-1,22
2926,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-29 16:14:58,NaN,-1,22
2946,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-1,-0.733399,2017-07-11 13:14:09,NaN,-1,22
2951,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-1,-0.733399,2017-07-25 14:52:53,NaN,-1,22
2965,Y,C_ID_a9af70f52d,-1,Y,1,B,879,M_ID_00a6ca8a8a,-4,-0.522637,2017-04-10 18:24:13,NaN,-1,29
2970,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-22 13:12:00,NaN,-1,22
2989,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-1,-0.733399,2017-07-04 13:05:49,NaN,-1,22
3030,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-08 13:10:42,NaN,-1,22
3935,N,C_ID_76ac7d7a48,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.743918,2017-12-08 22:02:10,NaN,-1,29
3958,N,C_ID_76ac7d7a48,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.743918,2017-12-08 22:00:25,NaN,-1,29
3968,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-5,-0.740897,2017-09-13 22:27:24,NaN,-1,29
3983,Y,C_ID_b45d4d37b1,-1,Y,2,C,665,M_ID_076cd8a829,-3,-0.177553,2017-11-06 19:24:53,NaN,-1,3
3984,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.736179,2018-02-06 18:14:14,NaN,-1,29
3987,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-4,0.514117,2017-10-26 19:39:40,NaN,-1,3
3988,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-4,-0.707073,2017-10-04 12:50:03,NaN,-1,29
3999,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-2,0.175420,2017-12-07 17:46:41,NaN,-1,3
4006,Y,C_ID_b45d4d37b1,-1,Y,6,C,491,M_ID_79692349d6,-6,2.925226,2017-08-25 15:34:05,NaN,-1,3
4012,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.738268,2018-02-19 17:53:46,NaN,-1,29
4013,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.734616,2018-02-17 08:43:44,NaN,-1,29
4035,N,C_ID_b45d4d37b1,-1,Y,3,C,550,M_ID_09d7a200d1,-2,1.005183,2017-12-14 16:45:52,NaN,-1,3
4037,N,C_ID_b45d4d37b1,-1,Y,3,C,550,M_ID_09d7a200d1,-2,1.005183,2017-12-15 02:46:35,NaN,-1,3
4043,Y,C_ID_b45d4d37b1,-1,Y,1,B,771,M_ID_eb21569741,-5,-0.496716,2017-09-19 00:01:28,NaN,-1,31
4055,N,C_ID_b45d4d37b1,-1,Y,6,C,550,M_ID_09d7a200d1,-6,1.970757,2017-08-28 12:09:44,NaN,-1,3
4064,Y,C_ID_b45d4d37b1,-1,Y,1,B,511,M_ID_28f1b3a0e7,-4,-0.548573,2017-10-09 18:33:39,NaN,-1,7
4082,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-4,-0.731971,2017-10-24 13:58:54,NaN,-1,29
4084,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.735322,2018-02-06 08:34:29,NaN,-1,29
4096,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-3,-0.204751,2017-11-05 02:16:58,NaN,-1,3
4099,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-5,-0.735488,2017-09-14 02:09:21,NaN,-1,29
4107,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-4,0.829373,2017-10-26 20:08:27,NaN,-1,3
4111,N,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-2,0.514117,2017-12-14 20:34:27,NaN,-1,3
4112,Y,C_ID_b45d4d37b1,-1,Y,3,C,491,M_ID_79692349d6,0,0.409157,2018-02-08 15:57:40,NaN,-1,3
4115,Y,C_ID_b45d4d37b1,-1,Y,4,C,665,M_ID_076cd8a829,-5,0.452058,2017-09-06 19:20:16,NaN,-1,3
4121,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.723812,2018-02-16 05:19:32,NaN,-1,29
4124,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.735322,2018-02-06 08:48:16,NaN,-1,29
4126,N,C_ID_b45d4d37b1,-1,Y,6,C,550,M_ID_09d7a200d1,-6,1.970757,2017-08-28 12:09:30,NaN,-1,3
4131,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.728485,2018-02-07 08:36:05,NaN,-1,29
4137,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.736179,2018-02-06 18:27:09,NaN,-1,29
4170,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_9139332ccc,0,-0.246194,2018-02-08 17:02:08,NaN,-1,29
4182,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.737712,2018-02-03 08:54:29,NaN,-1,29
4185,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_00a6ca8a8a,-3,-0.656749,2017-11-07 13:22:40,NaN,-1,29
4187,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.735352,2018-02-05 14:02:33,NaN,-1,29
4190,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.740897,2018-02-16 22:48:11,NaN,-1,29
4192,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-5,-0.726772,2017-09-13 22:41:26,NaN,-1,29
4193,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.735503,2018-01-26 13:44:13,NaN,-1,29
4195,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.297540,2017-12-13 18:19:04,NaN,-1,29
4212,Y,C_ID_b45d4d37b1,-1,Y,3,C,491,M_ID_79692349d6,0,3.253315,2018-02-08 12:13:13,NaN,-1,3
4217,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.730859,2017-11-14 17:56:45,NaN,-1,29
4237,Y,C_ID_b45d4d37b1,-1,Y,2,C,511,M_ID_32e6648d9b,-1,0.771611,2018-01-05 13:22:03,NaN,-1,7
4238,Y,C_ID_b45d4d37b1,-1,Y,2,C,491,M_ID_79692349d6,-3,-0.277029,2017-11-05 01:19:55,NaN,-1,3
4244,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.730394,2018-01-28 20:42:04,NaN,-1,29
4253,Y,C_ID_b45d4d37b1,-1,Y,3,C,550,M_ID_09d7a200d1,-4,1.005183,2017-10-26 20:33:33,NaN,-1,3
4254,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.735683,2018-01-31 13:51:58,NaN,-1,29
4277,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.297540,2017-12-18 14:58:08,NaN,-1,29
4281,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.737456,2018-02-17 08:52:40,NaN,-1,29
4288,Y,C_ID_b45d4d37b1,-1,Y,1,B,771,M_ID_eb21569741,-5,-0.644412,2017-09-13 21:13:41,NaN,-1,31
4298,Y,C_ID_b45d4d37b1,-1,Y,1,B,661,M_ID_fc7d7969c3,0,-0.717005,2018-02-11 13:57:59,NaN,-1,8
4317,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.736705,2018-02-03 11:48:05,NaN,-1,29
4318,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-2,0.061218,2017-12-07 17:32:13,NaN,-1,3
4327,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.737111,2018-02-17 12:07:05,NaN,-1,29
4333,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.728590,2018-02-07 15:17:44,NaN,-1,29
4334,Y,C_ID_b45d4d37b1,-1,Y,2,C,665,M_ID_076cd8a829,-3,-0.177553,2017-11-06 19:39:57,NaN,-1,3
4339,Y,C_ID_b45d4d37b1,-1,Y,2,C,879,M_ID_9139332ccc,-5,-0.238351,2017-09-13 12:38:50,NaN,-1,29
4364,Y,C_ID_b45d4d37b1,-1,Y,2,C,879,M_ID_9139332ccc,-2,0.188478,2017-12-12 22:24:39,NaN,-1,29
4375,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.731686,2018-01-31 14:29:09,NaN,-1,29
4378,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_9139332ccc,-5,-0.339088,2017-09-17 12:08:30,NaN,-1,29
5451,N,C_ID_3917d75318,-1,Y,1,B,879,M_ID_b9dcf28cb9,-2,-0.468917,2017-12-01 21:14:05,NaN,-1,29
6470,Y,C_ID_ad99f08d4c,-1,Y,5,C,879,M_ID_00a6ca8a8a,-4,0.632135,2017-10-27 11:34:58,NaN,-1,29
6481,Y,C_ID_ad99f08d4c,-1,Y,5,C,879,M_ID_00a6ca8a8a,-4,0.632135,2017-10-27 12:00:41,NaN,-1,29
6573,Y,C_ID_ad99f08d4c,-1,Y,5,C,879,M_ID_00a6ca8a8a,-4,0.632135,2017-10-27 11:30:39,NaN,-1,29
6603,Y,C_ID_e5f5fcf6e7,-1,Y,4,C,665,M_ID_076cd8a829,-3,1.329215,2017-11-16 10:54:27,NaN,-1,3
6606,Y,C_ID_e5f5fcf6e7,-1,Y,1,B,550,M_ID_09d7a200d1,-2,-0.599648,2017-12-06 15:56:50,NaN,-1,3
6616,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,550,M_ID_09d7a200d1,-3,1.434671,2017-11-08 14:31:23,NaN,-1,3
6636,Y,C_ID_e5f5fcf6e7,-1,Y,3,C,550,M_ID_09d7a200d1,-2,-0.231498,2017-12-06 11:54:42,NaN,-1,3
6646,N,C_ID_e5f5fcf6e7,-1,Y,6,C,690,M_ID_3111c6df35,-6,2.201279,2017-08-26 16:35:41,NaN,-1,1
6654,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,-0.115674,2017-08-24 15:02:31,NaN,-1,29
6673,N,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,-0.553907,2017-08-26 16:35:38,NaN,-1,29
6710,Y,C_ID_e5f5fcf6e7,-1,Y,4,C,665,M_ID_076cd8a829,-8,0.725796,2017-06-03 12:12:30,NaN,-1,3
6730,Y,C_ID_e5f5fcf6e7,-1,Y,4,C,665,M_ID_076cd8a829,-9,0.148702,2017-05-02 12:44:49,NaN,-1,3
6750,N,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,-0.553907,2017-08-26 16:35:39,NaN,-1,29
6752,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,-0.553907,2017-08-26 16:50:48,NaN,-1,29
6784,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,690,M_ID_3111c6df35,-6,2.201279,2017-08-26 16:50:50,NaN,-1,1
6815,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,2.978615,2017-08-24 15:02:32,NaN,-1,29
6929,N,C_ID_72b66c75ad,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.745405,2017-12-19 11:26:15,NaN,-1,29
6961,N,C_ID_72b66c75ad,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.742400,2017-12-19 11:26:12,NaN,-1,29
7084,Y,C_ID_190bd090c9,-1,Y,1,B,755,M_ID_445742726b,-10,-0.716855,2017-02-21 06:20:45,NaN,-1,8
7099,Y,C_ID_190bd090c9,-1,Y,1,B,755,M_ID_445742726b,-9,-0.716855,2017-03-12 20:46:53,NaN,-1,8
7675,Y,C_ID_536bff298a,-1,Y,1,B,511,M_ID_9139332ccc,-11,-0.559076,2017-03-27 10:41:11,NaN,-1,7
7683,N,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-10,-0.584772,2017-04-27 23:59:19,NaN,-1,29
7695,N,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-10,-0.607327,2017-04-26 00:04:49,NaN,-1,29
7696,N,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.401298,2017-12-04 12:00:22,NaN,-1,29
7698,N,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-10,-0.584772,2017-04-26 12:58:52,NaN,-1,29
7705,Y,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-1,-0.659904,2018-01-31 23:26:37,NaN,-1,29
7707,Y,C_ID_536bff298a,-1,Y,1,B,755,M_ID_86be58d7e0,-3,-0.686802,2017-11-29 15:06:37,NaN,-1,8
7708,Y,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.641737,2017-10-30 05:14:38,NaN,-1,29
7709,Y,C_ID_536bff298a,-1,Y,2,C,879,M_ID_9139332ccc,-2,-0.385430,2017-12-04 12:12:31,NaN,-1,29
7712,N,C_ID_536bff298a,-1,Y,1,B,511,M_ID_9139332ccc,-11,-0.559076,2017-03-27 00:56:46,NaN,-1,7
9410,Y,C_ID_a1b71153bd,-1,Y,1,B,690,M_ID_3111c6df35,-2,-0.371260,2017-11-10 18:58:00,NaN,-1,1
9421,Y,C_ID_a1b71153bd,-1,Y,2,C,834,M_ID_29ec8d2ab8,-3,-0.598145,2017-10-24 18:39:08,NaN,-1,27
9424,Y,C_ID_a1b71153bd,-1,Y,2,C,690,M_ID_3111c6df35,-4,-0.596658,2017-09-11 20:47:07,NaN,-1,1
9426,Y,C_ID_a1b71153bd,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.612000,2017-09-11 19:39:33,NaN,-1,29
9548,N,C_ID_d6f97e5780,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.740897,2018-02-07 17:18:45,NaN,-1,29
9642,N,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-8,-0.640520,2017-06-12 20:46:21,NaN,-1,16
9644,Y,C_ID_3df86e0089,-1,Y,1,B,884,M_ID_9dbbaabb0a,-10,-0.584802,2017-04-13 14:30:04,NaN,-1,27
9645,Y,C_ID_3df86e0089,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.627026,2017-12-04 14:38:35,NaN,-1,29
9646,Y,C_ID_3df86e0089,-1,Y,1,B,683,M_ID_94eea62513,-3,-0.612931,2017-11-13 14:26:51,NaN,-1,34
9647,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_7bb972553c,-10,-0.578010,2017-04-02 13:05:48,NaN,-1,16
9649,Y,C_ID_3df86e0089,-1,Y,1,B,561,M_ID_4d3d928d6f,-6,-0.686952,2017-08-28 13:45:36,NaN,-1,7
9650,N,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-8,-0.640520,2017-06-12 20:46:22,NaN,-1,16
9651,Y,C_ID_3df86e0089,-1,Y,1,B,705,M_ID_2105757cda,-12,-0.411531,2017-02-13 15:40:57,NaN,-1,33
9652,N,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-12,-0.178996,2017-02-10 12:11:00,NaN,-1,16
9653,N,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-12,-0.178996,2017-02-10 12:10:17,NaN,-1,16
9655,Y,C_ID_3df86e0089,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.521525,2017-10-09 16:00:29,NaN,-1,29
9656,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_7bb972553c,-12,-0.595501,2017-02-27 12:55:21,NaN,-1,16
9659,Y,C_ID_3df86e0089,-1,Y,1,B,561,M_ID_4d3d928d6f,-12,-0.686952,2017-02-26 18:15:33,NaN,-1,7
9660,Y,C_ID_3df86e0089,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.476461,2017-10-09 16:08:46,NaN,-1,29
9661,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-11,-0.467760,2017-03-10 15:24:13,NaN,-1,16
9662,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_7bb972553c,-2,-0.239718,2017-12-13 13:20:10,NaN,-1,16
9663,Y,C_ID_3df86e0089,-1,Y,1,B,561,M_ID_4d3d928d6f,-1,-0.686952,2018-01-28 07:55:53,NaN,-1,7
9664,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_7bb972553c,-8,-0.652421,2017-06-13 12:52:39,NaN,-1,16
9667,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_2a95494c5a,-11,-0.591834,2017-03-06 15:26:44,NaN,-1,16
9668,Y,C_ID_3df86e0089,-1,Y,1,B,879,M_ID_9139332ccc,0,-0.636012,2018-02-22 13:20:42,NaN,-1,29
9669,Y,C_ID_3df86e0089,-1,Y,1,B,690,M_ID_c9855bf3e3,-11,-0.617680,2017-03-29 14:56:29,NaN,-1,1
9670,Y,C_ID_3df86e0089,-1,Y,2,C,834,M_ID_29ec8d2ab8,-9,-0.401448,2017-05-08 16:27:11,NaN,-1,27
9671,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-7,-0.661527,2017-07-23 14:12:08,NaN,-1,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29111665,Y,C_ID_92039ab1ac,-1,Y,1,B,879,M_ID_9139332ccc,-5,-0.489804,2017-07-26 09:41:45,NaN,-1,29
29111666,N,C_ID_92039ab1ac,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.587927,2017-08-09 15:45:58,NaN,-1,29
29111698,Y,C_ID_4efb62f6b5,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.743918,2017-12-13 19:14:59,NaN,-1,29
29111700,Y,C_ID_97aaf28100,-1,Y,2,C,879,M_ID_00a6ca8a8a,-2,-0.476431,2017-12-12 19:37:13,NaN,-1,29
29111704,N,C_ID_f8596d4a71,-1,Y,1,B,734,M_ID_51edbd1782,-9,-0.626696,2017-05-02 20:47:28,NaN,-1,25
29111705,Y,C_ID_f8596d4a71,-1,Y,1,B,755,M_ID_86be58d7e0,-6,-0.686952,2017-08-10 17:10:16,NaN,-1,8
29111706,Y,C_ID_f8596d4a71,-1,Y,1,B,755,M_ID_86be58d7e0,-3,-0.686817,2017-11-05 08:19:29,NaN,-1,8
29111707,Y,C_ID_f8596d4a71,-1,Y,1,B,755,M_ID_86be58d7e0,0,-0.686817,2018-02-05 08:02:07,NaN,-1,8

In [18]:
history.groupby('card_id').category_1.unique()

card_id
C_ID_00007093c1    [N, Y]
C_ID_0001238066    [N, Y]
C_ID_0001506ef0       [N]
C_ID_0001793786    [N, Y]
C_ID_000183fdda    [N, Y]
C_ID_00024e244b       [N]
C_ID_0002709b5a    [N, Y]
C_ID_00027503e2       [N]
C_ID_000298032a       [N]
C_ID_0002ba3c2e       [N]
C_ID_0002c7c2c1       [N]
C_ID_00032df08f    [N, Y]
C_ID_0003754056       [N]
C_ID_000377f6a0       [N]
C_ID_0003be3c83    [N, Y]
C_ID_0003f41435       [N]
C_ID_00042d509c    [Y, N]
C_ID_0004587331    [N, Y]
C_ID_0004725b87       [N]
C_ID_0004888ddd    [N, Y]
C_ID_0004b68c49    [Y, N]
C_ID_0004c2a5ab    [Y, N]
C_ID_00057b99fe       [N]
C_ID_000599daf9       [N]
C_ID_0005b2f279       [N]
C_ID_0005b5804f       [N]
C_ID_0005f16cc8    [N, Y]
C_ID_0006152db8    [N, Y]
C_ID_000616f4a8    [N, Y]
C_ID_000664aa02       [N]
C_ID_00079fec55    [Y, N]
C_ID_0007a60a33       [N]
C_ID_0007fe3157    [N, Y]
C_ID_000844d8f1       [N]
C_ID_0008461020    [N, Y]
C_ID_00087f3079       [N]
C_ID_0009010641    [Y, N]
C_ID_0009150c11       [N]
C_ID_000950bc78    [N, Y]
C_ID_00099cb909       [N]
C_ID_0009ae74c1    [N, Y]
C_ID_0009d25138    [N, Y]
C_ID_0009ef1dc2       [N]
C_ID_000a6044e9    [N, Y]
C_ID_000a9864df    [N, Y]
C_ID_000aa2220e    [N, Y]
C_ID_000acab1f6    [N, Y]
C_ID_000b0305d9    [N, Y]
C_ID_000b13135b    [N, Y]
C_ID_000b24f797    [N, Y]
C_ID_000b3dbdea       [N]
C_ID_000b503737    [N, Y]
C_ID_000b72c028    [N, Y]
C_ID_000c00fc96       [N]
C_ID_000c1a998b    [N, Y]
C_ID_000c778b05       [N]
C_ID_000c8010ac    [Y, N]
C_ID_000cadb0f6    [Y, N]
C_ID_000cadb59e    [N, Y]
C_ID_000ce910cb    [Y, N]
C_ID_000cfb6503       [N]
C_ID_000d005e43       [N]
C_ID_000d0a81c5    [N, Y]
C_ID_000d22fabd       [N]
C_ID_000dd1a097       [N]
C_ID_000dd8c722       [N]
C_ID_000dfced4d       [N]
C_ID_000e0c94f7    [N, Y]
C_ID_000e19e469       [N]
C_ID_000e518263    [Y, N]
C_ID_000edf11d7       [N]
C_ID_000ee9a514    [N, Y]
C_ID_000ef9e20b       [N]
C_ID_000f023e16       [N]
C_ID_000f2de962    [N, Y]
C_ID_000f4ebb37       [N]
C_ID_000f6fea6a    [N, Y]
C_ID_000f76201e    [Y, N]
C_ID_000f7b7753       [N]
C_ID_000f7e3e49    [Y, N]
C_ID_000fbd9928       [N]
C_ID_000fc266be       [N]
C_ID_000fd44a39    [N, Y]
C_ID_0010376f50       [N]
C_ID_0010779aaf    [Y, N]
C_ID_0011057de1    [N, Y]
C_ID_0011762232       [N]
C_ID_00117c1aeb       [N]
C_ID_00117f101b       [N]
C_ID_00119bb665       [N]
C_ID_0011a89fcc    [N, Y]
C_ID_0011c836e7       [N]
C_ID_0011e63c0d       [N]
C_ID_0011ee467f    [Y, N]
C_ID_00122c3b8d    [N, Y]
C_ID_00127204f5       [N]
C_ID_001272c2c6    [N, Y]
C_ID_00128a24cf       [N]
C_ID_0012bcf581       [N]
C_ID_00130ac58d       [N]
C_ID_00136926d8       [N]
C_ID_0013f936f0       [N]
C_ID_001454b74c    [N, Y]
C_ID_001482362b    [N, Y]
C_ID_00149a71a4       [N]
C_ID_00151200a5       [N]
C_ID_0015677437       [N]
C_ID_0015cb7ed9    [N, Y]
C_ID_0015e02e4c       [N]
C_ID_0015f549cb       [N]
C_ID_0016563f06    [N, Y]
C_ID_00165af96d       [N]
C_ID_001676af4f    [Y, N]
C_ID_00167ca6d8       [N]
C_ID_00169b9828       [N]
C_ID_0016b189b4    [N, Y]
C_ID_0016e257a5    [N, Y]
C_ID_0016eb652c       [N]
C_ID_0017c2ec57       [N]
C_ID_0017dadfd5    [N, Y]
C_ID_0017fee682    [N, Y]
C_ID_00186a15ce       [N]
C_ID_00187526cf    [N, Y]
C_ID_0018bfbe9d    [N, Y]
C_ID_00191957a1    [N, Y]
C_ID_00192a74ce    [N, Y]
C_ID_00196c38d5    [N, Y]
C_ID_001982552a    [N, Y]
C_ID_001a1de282       [N]
C_ID_001aa75740    [Y, N]
C_ID_001acb9182       [N]
C_ID_001addb9d7    [N, Y]
C_ID_001ae38fdf    [N, Y]
C_ID_001b3f2dd2       [N]
C_ID_001b43d48f    [N, Y]
C_ID_001b4c5151    [Y, N]
C_ID_001b68a34b    [N, Y]
C_ID_001b81c304    [N, Y]
C_ID_001b853b44       [N]
C_ID_001b9c4a97    [N, Y]
C_ID_001bd2c99c       [N]
C_ID_001bd54f5e    [N, Y]
C_ID_001bdd0f69       [N]
C_ID_001c09a36b       [Y]
C_ID_001c1581a8       [N]
C_ID_001cb1aa86       [N]
C_ID_001cbc2343    [N, Y]
C_ID_001d401a8c       [N]
C_ID_001d7f9262       [N]
C_ID_001da949e5       [N]
C_ID_001db316bf    [Y, N]
C_ID_001de6764b    [Y, N]
C_ID_001e0c63c7    [N, Y]
C_ID_001e2bb2ce       [N]
C_ID_001e4e94e5       [N]
C_ID_001f019c09       [N]
C_ID_001f2d7b8c    [N, Y]
C_ID_001fb79a42       [N]
C_ID_001fc7b4d5    [N, Y]
C_ID_001fd0fe89       [N]
C_ID_00201d9bd1       [N]
C_ID_00201eee66    [N, Y]
C_ID_0020246399       [N]
C_ID_0020e01cf5    [N, Y]
C_ID_0020f8197d       [N]
C_ID_00210d1bff       [N]
C_ID_00216bdb6a       [N]
C_ID_002198cdf1       [N]
C_ID_0021ea1fb7       [N]
C_ID_002249e66d    [N, Y]
C_ID_002263a16a    [N, Y]
C_ID_0022ce1648    [N, Y]
C_ID_0022d08784       [N]
C_ID_002315a188       [N]
C_ID_002315dc90    [N, Y]
C_ID_00232be11f       [N]
C_ID_0023e2c382    [Y, N]
C_ID_0023faafd2       [N]
C_ID_0024770552       [N]
C_ID_0024aaee36       [N]
C_ID_0024e3b7d7       [N]
C_ID_0024ec2d9c       [N]
C_ID_00251f994c    [Y, N]
C_ID_00254bc137       [N]
C_ID_0025a6dbe7    [N, Y]
C_ID_0026850f57       [N]
C_ID_002776e95a    [N, Y]
C_ID_002780b4cf    [N, Y]
C_ID_0027d7e25e       [N]
C_ID_00286850f5    [N, Y]
C_ID_002887180d       [N]
C_ID_0028ac8028       [N]
C_ID_0028c1608e       [N]
C_ID_0028e15a78       [Y]
C_ID_00290b8994    [N, Y]
C_ID_002936ada6    [N, Y]
C_ID_0029435cf6       [N]
C_ID_00298b7d14       [N]
C_ID_0029d52418    [Y, N]
C_ID_0029ede787       [N]
                    ...
C_ID_ffdc5009c1       [N]
C_ID_ffdc82f906       [N]
C_ID_ffdca28518    [N, Y]
C_ID_ffdcc94d1f       [N]
C_ID_ffdcd19708    [N, Y]
C_ID_ffdcdfc623       [N]
C_ID_ffdd77f2de    [Y, N]
C_ID_ffddd6feb9    [N, Y]
C_ID_ffddfebbf5       [N]
C_ID_ffde58aa74    [N, Y]
C_ID_ffdee57646       [N]
C_ID_ffdf22a70e       [N]
C_ID_ffdf5b6f63       [N]
C_ID_ffdf5e0a5d       [N]
C_ID_ffdf8608e4       [N]
C_ID_ffdf9871b8       [N]
C_ID_ffdf9cd58e       [N]
C_ID_ffdfb5f8e3    [Y, N]
C_ID_ffdfb75892       [N]
C_ID_ffdfdf7264    [Y, N]
C_ID_ffdfffc597       [N]
C_ID_ffe0195528       [N]
C_ID_ffe0232b20       [N]
C_ID_ffe044a946    [N, Y]
C_ID_ffe04f03a1    [Y, N]
C_ID_ffe060b506    [Y, N]
C_ID_ffe072a280    [Y, N]
C_ID_ffe088e166       [N]
C_ID_ffe08ab076       [N]
C_ID_ffe0be1342    [N, Y]
C_ID_ffe0d0ddb9       [N]
C_ID_ffe0fbaecd       [N]
C_ID_ffe1192b9d    [Y, N]
C_ID_ffe15e812b    [Y, N]
C_ID_ffe16cfd99       [N]
C_ID_ffe1a60d1c       [N]
C_ID_ffe1bf3c5a    [N, Y]
C_ID_ffe21478f1       [N]
C_ID_ffe214bc43       [N]
C_ID_ffe216e5a1       [N]
C_ID_ffe2a5b3f9       [N]
C_ID_ffe2a75820       [N]
C_ID_ffe2e4af9c       [N]
C_ID_ffe308727f    [N, Y]
C_ID_ffe3107dae       [N]
C_ID_ffe37f9923    [N, Y]
C_ID_ffe390749d       [Y]
C_ID_ffe39f6c88       [N]
C_ID_ffe3bdc3d6       [N]
C_ID_ffe4eb895f       [N]
C_ID_ffe513f669    [N, Y]
C_ID_ffe545e848    [N, Y]
C_ID_ffe56e0c89    [N, Y]
C_ID_ffe5cb03ac    [N, Y]
C_ID_ffe609698f       [N]
C_ID_ffe670105f       [N]
C_ID_ffe688fd68    [Y, N]
C_ID_ffe6a84c59    [Y, N]
C_ID_ffe6dcc805       [N]
C_ID_ffe703f745    [N, Y]
C_ID_ffe71ec373       [N]
C_ID_ffe754d10c       [N]
C_ID_ffe7871f38       [N]
C_ID_ffe791f795       [N]
C_ID_ffe7a0256d       [N]
C_ID_ffe80c5734       [N]
C_ID_ffe83ac1ec       [N]
C_ID_ffe85078c8    [N, Y]
C_ID_ffe8541af1    [N, Y]
C_ID_ffe85833bd    [N, Y]
C_ID_ffe8645e27    [N, Y]
C_ID_ffe8bf9ef2    [N, Y]
C_ID_ffe8e34523       [N]
C_ID_ffe9091205    [N, Y]
C_ID_ffe9338443       [N]
C_ID_ffe969e56f    [N, Y]
C_ID_ffe97acefc    [N, Y]
C_ID_ffe98a4674    [N, Y]
C_ID_ffe9944d60       [N]
C_ID_ffea783298       [N]
C_ID_ffea95ca66       [N]
C_ID_ffeaa35463    [Y, N]
C_ID_ffeacaa081       [N]
C_ID_ffeb02d2bb       [N]
C_ID_ffeb0898b5    [Y, N]
C_ID_ffeb258d93       [N]
C_ID_ffeb978d3b    [N, Y]
C_ID_ffebe44c6d    [N, Y]
C_ID_ffebf84f15       [Y]
C_ID_ffec0ead94       [N]
C_ID_ffec3e797c    [N, Y]
C_ID_ffec483ae9    [Y, N]
C_ID_ffec615a26       [N]
C_ID_ffec69c581       [N]
C_ID_ffec7d3b3b       [N]
C_ID_ffec95782a       [N]
C_ID_ffecac6ec9       [N]
C_ID_ffecc9625f    [N, Y]
C_ID_ffeccd43c9       [N]
C_ID_ffece651ab       [N]
C_ID_ffed5c1f3e       [N]
C_ID_ffedb3bbdb    [N, Y]
C_ID_ffee45f941       [N]
C_ID_ffeec704aa    [N, Y]
C_ID_ffeec72833       [N]
C_ID_ffef6a5157    [N, Y]
C_ID_ffef724ee2    [Y, N]
C_ID_ffefdb10d6       [N]
C_ID_ffefee0a04    [N, Y]
C_ID_fff01c7ee1    [Y, N]
C_ID_fff04976bb       [N]
C_ID_fff04aa1f5       [N]
C_ID_fff0688a04    [Y, N]
C_ID_fff06f2aad       [N]
C_ID_fff0ec3a73       [N]
C_ID_fff0f2f9ce    [N, Y]
C_ID_fff115ef2e       [N]
C_ID_fff12bcae2       [N]
C_ID_fff13e9843    [Y, N]
C_ID_fff172a7fa    [Y, N]
C_ID_fff174b839       [N]
C_ID_fff17acd27       [N]
C_ID_fff184faf3       [N]
C_ID_fff1d3ae5f       [N]
C_ID_fff201065c       [N]
C_ID_fff21f3bbc    [N, Y]
C_ID_fff2946cca       [N]
C_ID_fff2ef437b       [N]
C_ID_fff33122b1       [N]
C_ID_fff34656e5       [N]
C_ID_fff38f8134    [N, Y]
C_ID_fff3b3d49e    [N, Y]
C_ID_fff3b465e4    [N, Y]
C_ID_fff3bcdb73    [N, Y]
C_ID_fff3c52f3c       [N]
C_ID_fff47dea33    [N, Y]
C_ID_fff4c4312c    [Y, N]
C_ID_fff4ec311a       [N]
C_ID_fff4ed08c5    [N, Y]
C_ID_fff50bff5e       [N]
C_ID_fff50ce0e0    [N, Y]
C_ID_fff56b7768       [N]
C_ID_fff5be9c03       [N]
C_ID_fff6341ea6    [Y, N]
C_ID_fff678cf7b    [N, Y]
C_ID_fff690bccc       [N]
C_ID_fff6974041       [N]
C_ID_fff6b4456b    [N, Y]
C_ID_fff6bf5305       [N]
C_ID_fff6e4fefb    [N, Y]
C_ID_fff7031631    [N, Y]
C_ID_fff74c6e55    [Y, N]
C_ID_fff7714bc3    [Y, N]
C_ID_fff796a3f9       [N]
C_ID_fff82c2722       [N]
C_ID_fff845b82f       [N]
C_ID_fff8874bc1    [N, Y]
C_ID_fff8d507b4       [N]
C_ID_fff8e0d7da       [N]
C_ID_fff91cdd28    [N, Y]
C_ID_fff96876e0       [N]
C_ID_fff9e6b8e4       [N]
C_ID_fffa2280c9    [N, Y]
C_ID_fffa2ced7d       [N]
C_ID_fffa362304       [Y]
C_ID_fffa99d1da    [N, Y]
C_ID_fffadd3551    [Y, N]
C_ID_fffaed41f0       [N]
C_ID_fffb59b27a       [Y]
C_ID_fffb67f260       [N]
C_ID_fffb79fb56       [N]
C_ID_fffb9ea3f6    [N, Y]
C_ID_fffba72dc5       [N]
C_ID_fffbdf036b       [N]
C_ID_fffbee5c24       [N]
C_ID_fffc96bf24    [N, Y]
C_ID_fffcb74f49    [N, Y]
C_ID_fffcf66e12       [N]
C_ID_fffd070e0e       [N]
C_ID_fffd1207a8       [N]
C_ID_fffd24dcf3    [N, Y]
C_ID_fffd337484    [N, Y]
C_ID_fffd345048       [N]
C_ID_fffd351e7f    [N, Y]
C_ID_fffd93c8bf       [N]
C_ID_fffd943b91    [N, Y]
C_ID_fffdad8aa0       [N]
C_ID_fffde15ab6    [N, Y]
C_ID_fffdf34798       [N]
C_ID_fffe29a04a       [N]
C_ID_fffe78b232    [N, Y]
C_ID_fffe866457       [N]
C_ID_fffea6de74    [N, Y]
C_ID_fffeced303    [Y, N]
C_ID_fffeed3a89    [N, Y]
C_ID_ffff1d9928    [N, Y]
C_ID_ffff579d3a       [N]
C_ID_ffff756266    [N, Y]
C_ID_ffff828181    [N, Y]
C_ID_fffffd5772    [Y, N]
Name: category_1, Length: 325540, dtype: object

In [26]:
history.city_id.value_counts(dropna=False)

 69     4835441
-1      2478624
 19     1151077
 158    1113013
 17      971714
 331     714414
 143     668769
 88      659328
 137     603023
 333     561144
 87      444940
 212     406196
 57      382232
 149     359540
 25      356757
 233     355108
 117     322414
 160     317617
 213     248371
 277     247294
 286     231877
 76      216048
 4       212403
 107     210182
 53      209668
 20      207650
 291     199983
 140     190359
 344     177694
 161     168745
 51      164222
 283     163347
 322     153926
 21      149278
 246     139898
 179     138888
 200     137668
 231     137245
 244     133140
 138     132244
 169     132161
 289     131576
 116     128194
 340     124669
 60      118852
 251     118368
 248     117916
 96      110001
 1       108519
 274     106563
 302     106447
 199     101660
 314      99370
 12       96647
 11       92785
 8        89353
 30       83598
 110      83196
 279      79094
 90       77047
 24       74184
 42       72730
 334      70606
 33       67797
 159      66568
 320      65485
 14       64610
 64       63373
 280      62054
 188      61846
 48       60639
 288      60347
 210      60119
 278      59949
 173      59400
 147      58555
 131      58055
 339      56509
 271      56498
 126      56107
 168      55587
 276      55257
 34       55131
 189      53926
 171      53067
 109      51310
 297      50198
 247      50058
 78       49755
 102      49716
 300      48781
 292      48490
 174      47294
 268      46863
 242      46777
 282      46600
 232      46396
 56       45031
 155      44379
 238      44245
 250      44014
 296      43958
 347      43617
 52       43539
 181      43034
 3        42665
 209      42602
 308      42460
 272      41248
 135      40805
 219      39866
 36       39374
 253      39269
 136      38474
 323      37486
 66       37484
 226      37217
 211      37213
 125      36500
 157      36153
 259      35703
 245      35595
 79       35580
 329      35343
 41       35269
 330      34942
 97       34579
 162      34238
 29       34057
 261      33605
 10       33395
 13       32701
 234      32691
 256      32253
 170      31750
 341      31500
 62       31310
 156      31019
 218      30841
 124      30717
 191      30491
 94       30104
 325      29257
 295      28073
 129      28069
 318      27786
 304      27744
 148      27391
 98       27093
 223      26834
 163      26388
 190      25983
 175      25906
 101      25705
 38       24953
 265      24948
 6        24220
 303      24206
 150      24077
 299      24032
 172      23928
 22       23707
 46       23671
 28       23586
 180      23267
 214      23260
 260      23251
 328      22886
 63       22705
 165      22645
 281      22636
 105      22582
 187      22541
 7        22477
 23       22236
 123      22115
 193      21699
 301      21367
 9        21053
 270      20984
 186      20898
 119      20846
 111      20666
 229      20642
 311      20513
 115      20461
 82       20458
 195      20391
 167      20387
 100      20313
 216      20003
 145      19852
 255      19653
 146      19296
 275      18958
 75       18752
 239      18711
 91       18663
 337      18568
 128      18459
 266      18330
 153      18263
 182      18191
 201      17918
 74       17841
 194      17838
 220      17813
 342      17622
 197      17456
 183      17431
 198      17335
 166      17292
 2        17171
 58       17124
 184      16977
 313      16710
 68       16562
 70       16500
 203      16424
 49       16300
 230      16250
 312      15860
 294      15828
 83       15762
 120      15655
 144      15622
 139      15579
 267      15384
 290      15307
 310      15240
 85       15153
 73       15084
 307      14958
 47       14893
 208      14803
 338      14757
 39       14481
 309      14435
 106      14349
 44       13862
 252      13617
 262      13005
 80       12786
 206      12764
 108      12732
 264      12595
 104      12590
 335      12474
 287      12197
 142      12139
 114      12126
 343      12113
 240      12018
 269      11918
 228      11857
 16       11747
 224      11685
 285      11654
 236      11264
 258      11056
 40       10959
 298      10661
 345      10424
 103      10170
 35       10128
 113      10084
 151       9986
 133       9872
 26        9845
 321       9808
 77        9736
 18        9565
 61        9458
 86        9372
 65        9352
 336       9022
 222       8819
 118       8518
 32        8382
 81        8278
 54        8201
 235       7918
 326       7912
 293       7804
 327       7499
 112       7461
 84        7367
 237       7285
 227       7233
 254       7143
 71        6781
 204       6745
 306       6128
 221       6096
 130       5657
 122       5458
 205       5385
 215       4791
 89        4760
 178       4430
 263       4003
 207       3905
 315       3845
 319       1645
 92         758
 273        620
 316        149
 185         45
Name: city_id, dtype: int64

In [28]:
history[history.city_id.isnull()]

Empty DataFrame
Columns: [authorized_flag, card_id, city_id, category_1, installments, category_3, merchant_category_id, merchant_id, month_lag, purchase_amount, purchase_date, category_2, state_id, subsector_id]
Index: []

In [31]:
sorted(history.state_id.value_counts().index)

[-1,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

* category2 > state > city > category1