# EDA
* 각 데이터 시트별로 살펴보겠습니다.

## 모듈 로드

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import gc

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
pd.set_option('display.max_columns', 400)
# pd.set_option('display.max_rows', 400)

## 데이터 로드

In [38]:
train = pd.read_csv(path + 'train.csv')

In [4]:
path = './data/'

In [7]:
history = pd.read_csv(path + 'historical_transactions.csv')

In [14]:
sorted(history.city_id.value_counts(dropna=False).index)

[-1,
 1,
 2,
 3,
 4,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 28,
 29,
 30,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 40,
 41,
 42,
 44,
 46,
 47,
 48,
 49,
 51,
 52,
 53,
 54,
 56,
 57,
 58,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 71,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 96,
 97,
 98,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 122,
 123,
 124,
 125,
 126,
 128,
 129,
 130,
 131,
 133,
 135,
 136,
 137,
 138,
 139,
 140,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 153,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 193,
 194,
 195,
 197,
 198,
 199,
 200,
 201,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 242,
 244,
 245,
 246,
 247,
 248,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 318,
 319,
 320,
 321,
 322,
 323,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 347]

In [83]:
history.groupby('card_id').purchase_date.min()

card_id
C_ID_00007093c1    2017-02-14 14:00:43
C_ID_0001238066    2017-09-28 22:25:14
C_ID_0001506ef0    2017-01-14 16:16:01
C_ID_0001793786    2017-01-21 10:15:21
C_ID_000183fdda    2017-08-07 09:49:14
C_ID_00024e244b    2017-01-02 15:11:20
C_ID_0002709b5a    2017-01-13 13:19:01
C_ID_00027503e2    2017-05-27 10:21:16
C_ID_000298032a    2017-02-13 12:18:36
C_ID_0002ba3c2e    2017-01-06 12:24:24
C_ID_0002c7c2c1    2017-04-15 15:18:49
C_ID_00032df08f    2017-01-05 16:13:46
C_ID_0003754056    2017-03-12 20:28:30
C_ID_000377f6a0    2017-03-11 20:36:54
C_ID_0003be3c83    2017-08-17 22:46:47
C_ID_0003f41435    2017-06-14 11:28:58
C_ID_00042d509c    2017-07-25 16:03:01
C_ID_0004587331    2017-09-27 17:55:23
C_ID_0004725b87    2017-01-07 17:05:48
C_ID_0004888ddd    2017-07-03 19:18:25
C_ID_0004b68c49    2017-09-25 01:40:18
C_ID_0004c2a5ab    2017-01-10 12:28:23
C_ID_00057b99fe    2017-01-21 21:46:10
C_ID_000599daf9    2017-04-15 09:22:15
C_ID_0005b2f279    2017-01-29 10:28:36
C_ID_0005b5804f    2017-07-15 12:56:04
C_ID_0005f16cc8    2017-01-02 22:48:42
C_ID_0006152db8    2017-06-23 20:23:57
C_ID_000616f4a8    2017-01-18 17:47:19
C_ID_000664aa02    2017-12-21 09:27:07
C_ID_00079fec55    2017-10-07 16:01:53
C_ID_0007a60a33    2017-06-03 13:23:32
C_ID_0007fe3157    2017-05-02 18:33:11
C_ID_000844d8f1    2017-07-23 11:41:24
C_ID_0008461020    2017-09-25 21:12:51
C_ID_00087f3079    2017-01-01 09:27:36
C_ID_0009010641    2017-07-19 19:05:15
C_ID_0009150c11    2017-05-27 08:20:02
C_ID_000950bc78    2017-09-09 13:38:24
C_ID_00099cb909    2017-09-22 00:12:46
C_ID_0009ae74c1    2017-01-05 19:17:36
C_ID_0009d25138    2017-04-11 15:54:26
C_ID_0009ef1dc2    2017-12-01 16:35:11
C_ID_000a6044e9    2017-02-08 17:40:05
C_ID_000a9864df    2017-10-11 19:29:16
C_ID_000aa2220e    2017-01-06 07:34:17
C_ID_000acab1f6    2017-01-16 21:21:31
C_ID_000b0305d9    2017-10-19 14:24:09
C_ID_000b13135b    2017-04-10 19:01:56
C_ID_000b24f797    2017-06-12 20:12:00
C_ID_000b3dbdea    2017-11-07 10:58:28
C_ID_000b503737    2017-01-12 21:37:46
C_ID_000b72c028    2017-10-18 14:55:51
C_ID_000c00fc96    2017-01-05 10:24:00
C_ID_000c1a998b    2017-10-09 20:37:25
C_ID_000c778b05    2017-06-25 15:07:34
C_ID_000c8010ac    2017-08-15 18:02:42
C_ID_000cadb0f6    2017-09-16 02:30:08
C_ID_000cadb59e    2017-01-04 14:42:42
C_ID_000ce910cb    2017-01-02 13:14:35
C_ID_000cfb6503    2017-01-05 22:26:01
C_ID_000d005e43    2017-10-31 17:40:23
C_ID_000d0a81c5    2017-10-13 00:00:00
C_ID_000d22fabd    2017-08-18 15:21:55
C_ID_000dd1a097    2017-12-12 09:44:42
C_ID_000dd8c722    2017-01-18 23:57:15
C_ID_000dfced4d    2017-01-10 08:46:16
C_ID_000e0c94f7    2017-11-18 18:25:15
C_ID_000e19e469    2017-09-01 18:01:41
C_ID_000e518263    2017-02-08 17:41:36
C_ID_000edf11d7    2017-11-25 00:00:00
C_ID_000ee9a514    2017-02-06 15:52:58
C_ID_000ef9e20b    2017-12-27 13:35:53
C_ID_000f023e16    2017-01-01 19:42:25
C_ID_000f2de962    2017-09-21 09:41:25
C_ID_000f4ebb37    2017-01-30 16:30:27
C_ID_000f6fea6a    2017-02-09 06:26:36
C_ID_000f76201e    2017-12-31 15:01:17
C_ID_000f7b7753    2017-07-10 14:28:43
C_ID_000f7e3e49    2017-05-21 08:59:23
C_ID_000fbd9928    2017-12-22 14:47:21
C_ID_000fc266be    2017-07-10 12:27:40
C_ID_000fd44a39    2017-11-10 23:25:35
C_ID_0010376f50    2017-01-09 21:35:06
C_ID_0010779aaf    2017-09-21 18:23:51
C_ID_0011057de1    2017-01-13 13:09:20
C_ID_0011762232    2017-10-11 16:55:11
C_ID_00117c1aeb    2017-01-25 09:20:29
C_ID_00117f101b    2017-02-27 16:26:22
C_ID_00119bb665    2017-02-15 07:24:08
C_ID_0011a89fcc    2017-02-06 17:25:39
C_ID_0011c836e7    2017-01-16 11:30:22
C_ID_0011e63c0d    2017-01-02 17:44:05
C_ID_0011ee467f    2017-07-28 21:54:51
C_ID_00122c3b8d    2017-01-23 16:40:18
C_ID_00127204f5    2017-03-03 19:10:23
C_ID_001272c2c6    2017-10-09 17:16:37
C_ID_00128a24cf    2017-01-02 09:07:54
C_ID_0012bcf581    2017-01-05 18:54:04
C_ID_00130ac58d    2017-06-12 23:05:17
C_ID_00136926d8    2017-12-11 14:27:33
C_ID_0013f936f0    2017-01-03 16:52:47
C_ID_001454b74c    2017-04-15 18:16:18
C_ID_001482362b    2017-09-04 19:40:13
C_ID_00149a71a4    2017-09-04 20:15:45
C_ID_00151200a5    2017-01-04 21:26:29
C_ID_0015677437    2017-10-04 20:10:06
C_ID_0015cb7ed9    2017-05-17 14:49:00
C_ID_0015e02e4c    2017-01-02 20:15:30
C_ID_0015f549cb    2017-01-15 17:38:59
C_ID_0016563f06    2017-09-30 18:23:09
C_ID_00165af96d    2017-04-07 20:56:37
C_ID_001676af4f    2017-08-12 16:47:24
C_ID_00167ca6d8    2017-01-05 01:03:48
C_ID_00169b9828    2017-01-02 00:15:45
C_ID_0016b189b4    2017-07-28 12:06:56
C_ID_0016e257a5    2017-11-11 23:18:49
C_ID_0016eb652c    2017-01-06 19:13:56
C_ID_0017c2ec57    2017-11-29 00:00:00
C_ID_0017dadfd5    2017-01-16 18:08:29
C_ID_0017fee682    2017-10-06 23:16:28
C_ID_00186a15ce    2017-02-26 11:32:16
C_ID_00187526cf    2017-01-13 20:22:20
C_ID_0018bfbe9d    2017-10-09 12:12:03
C_ID_00191957a1    2017-01-08 10:10:30
C_ID_00192a74ce    2017-09-23 15:35:25
C_ID_00196c38d5    2017-12-15 14:03:21
C_ID_001982552a    2017-02-08 11:57:17
C_ID_001a1de282    2017-12-18 08:25:16
C_ID_001aa75740    2017-10-08 21:22:26
C_ID_001acb9182    2017-09-15 12:33:38
C_ID_001addb9d7    2017-06-12 15:44:37
C_ID_001ae38fdf    2017-08-07 16:23:06
C_ID_001b3f2dd2    2017-08-28 11:57:46
C_ID_001b43d48f    2017-06-02 19:43:20
C_ID_001b4c5151    2017-02-01 15:57:20
C_ID_001b68a34b    2017-03-24 01:33:14
C_ID_001b81c304    2017-11-19 13:50:08
C_ID_001b853b44    2017-12-01 14:46:14
C_ID_001b9c4a97    2017-01-07 18:31:39
C_ID_001bd2c99c    2017-10-30 12:03:59
C_ID_001bd54f5e    2017-09-29 17:27:46
C_ID_001bdd0f69    2017-01-30 22:54:01
C_ID_001c09a36b    2017-01-09 13:20:24
C_ID_001c1581a8    2017-01-09 15:00:16
C_ID_001cb1aa86    2017-04-06 12:28:15
C_ID_001cbc2343    2017-08-28 17:56:43
C_ID_001d401a8c    2017-01-20 13:08:12
C_ID_001d7f9262    2017-12-05 13:22:51
C_ID_001da949e5    2017-08-18 18:47:45
C_ID_001db316bf    2017-02-06 07:56:26
C_ID_001de6764b    2017-03-26 19:00:26
C_ID_001e0c63c7    2017-01-20 16:21:44
C_ID_001e2bb2ce    2017-06-16 15:36:47
C_ID_001e4e94e5    2017-05-05 20:13:06
C_ID_001f019c09    2017-02-16 17:09:25
C_ID_001f2d7b8c    2017-01-23 18:27:55
C_ID_001fb79a42    2017-03-29 11:27:20
C_ID_001fc7b4d5    2017-08-19 00:29:02
C_ID_001fd0fe89    2017-08-08 18:43:11
C_ID_00201d9bd1    2017-08-01 14:51:37
C_ID_00201eee66    2017-01-05 07:49:57
C_ID_0020246399    2017-03-14 08:45:53
C_ID_0020e01cf5    2017-08-28 13:42:36
C_ID_0020f8197d    2017-06-14 12:26:17
C_ID_00210d1bff    2017-01-12 23:31:33
C_ID_00216bdb6a    2017-01-24 10:47:06
C_ID_002198cdf1    2017-08-17 16:00:59
C_ID_0021ea1fb7    2017-07-01 09:43:16
C_ID_002249e66d    2017-01-17 14:49:09
C_ID_002263a16a    2017-01-24 10:25:17
C_ID_0022ce1648    2017-08-02 16:31:35
C_ID_0022d08784    2017-03-01 15:03:04
C_ID_002315a188    2017-01-04 10:55:11
C_ID_002315dc90    2017-01-04 18:36:08
C_ID_00232be11f    2017-11-09 21:52:23
C_ID_0023e2c382    2017-02-21 18:09:28
C_ID_0023faafd2    2017-05-15 17:30:21
C_ID_0024770552    2017-02-07 10:14:26
C_ID_0024aaee36    2017-01-03 15:29:03
C_ID_0024e3b7d7    2017-11-28 00:00:00
C_ID_0024ec2d9c    2017-07-21 17:13:50
C_ID_00251f994c    2017-12-20 18:50:24
C_ID_00254bc137    2017-01-10 19:37:44
C_ID_0025a6dbe7    2017-05-08 18:11:39
C_ID_0026850f57    2017-02-25 19:54:26
C_ID_002776e95a    2017-10-20 00:00:00
C_ID_002780b4cf    2017-08-21 15:21:03
C_ID_0027d7e25e    2017-01-24 23:08:51
C_ID_00286850f5    2017-05-04 13:27:33
C_ID_002887180d    2017-01-09 15:52:53
C_ID_0028ac8028    2017-01-06 13:58:13
C_ID_0028c1608e    2017-01-02 12:11:24
C_ID_0028e15a78    2017-10-25 15:07:28
C_ID_00290b8994    2017-07-02 16:03:57
C_ID_002936ada6    2017-01-03 18:23:17
C_ID_0029435cf6    2017-11-24 14:18:26
C_ID_00298b7d14    2017-02-03 17:45:08
C_ID_0029d52418    2017-01-02 17:05:51
C_ID_0029ede787    2017-12-15 11:39:54
                          ...
C_ID_ffdc5009c1    2017-01-04 12:26:05
C_ID_ffdc82f906    2017-01-05 13:17:08
C_ID_ffdca28518    2017-10-15 08:00:00
C_ID_ffdcc94d1f    2017-01-21 16:07:38
C_ID_ffdcd19708    2017-01-06 12:27:28
C_ID_ffdcdfc623    2017-01-19 22:05:08
C_ID_ffdd77f2de    2017-03-21 19:16:08
C_ID_ffddd6feb9    2017-11-26 13:11:01
C_ID_ffddfebbf5    2017-01-02 15:03:52
C_ID_ffde58aa74    2017-04-19 17:25:50
C_ID_ffdee57646    2017-02-20 18:58:39
C_ID_ffdf22a70e    2017-01-04 15:19:34
C_ID_ffdf5b6f63    2017-11-17 19:44:16
C_ID_ffdf5e0a5d    2017-02-28 10:09:48
C_ID_ffdf8608e4    2017-02-27 15:45:00
C_ID_ffdf9871b8    2017-04-16 21:21:09
C_ID_ffdf9cd58e    2017-02-07 13:35:32
C_ID_ffdfb5f8e3    2017-01-30 02:43:13
C_ID_ffdfb75892    2017-03-22 13:21:37
C_ID_ffdfdf7264    2017-12-05 13:57:37
C_ID_ffdfffc597    2017-01-06 14:37:13
C_ID_ffe0195528    2017-11-03 22:00:36
C_ID_ffe0232b20    2017-09-20 15:17:25
C_ID_ffe044a946    2017-05-14 15:53:07
C_ID_ffe04f03a1    2017-11-11 11:24:29
C_ID_ffe060b506    2017-06-01 19:36:22
C_ID_ffe072a280    2017-01-14 15:58:30
C_ID_ffe088e166    2017-01-28 12:30:28
C_ID_ffe08ab076    2017-11-28 22:14:17
C_ID_ffe0be1342    2017-05-06 19:50:30
C_ID_ffe0d0ddb9    2017-02-02 12:41:39
C_ID_ffe0fbaecd    2017-01-03 12:49:16
C_ID_ffe1192b9d    2017-01-21 12:54:53
C_ID_ffe15e812b    2017-04-27 20:11:08
C_ID_ffe16cfd99    2017-01-07 07:50:55
C_ID_ffe1a60d1c    2017-04-01 14:35:26
C_ID_ffe1bf3c5a    2017-05-16 14:54:24
C_ID_ffe21478f1    2017-11-24 18:26:35
C_ID_ffe214bc43    2017-04-17 20:57:28
C_ID_ffe216e5a1    2017-05-20 10:50:32
C_ID_ffe2a5b3f9    2017-01-06 23:51:41
C_ID_ffe2a75820    2017-01-04 13:17:34
C_ID_ffe2e4af9c    2017-01-04 12:08:52
C_ID_ffe308727f    2017-01-04 07:51:20
C_ID_ffe3107dae    2017-01-30 19:04:48
C_ID_ffe37f9923    2017-01-06 19:58:14
C_ID_ffe390749d    2017-01-09 15:51:03
C_ID_ffe39f6c88    2017-08-17 16:48:31
C_ID_ffe3bdc3d6    2017-01-02 16:16:31
C_ID_ffe4eb895f    2017-05-13 15:04:17
C_ID_ffe513f669    2017-01-07 17:13:44
C_ID_ffe545e848    2017-01-05 13:32:51
C_ID_ffe56e0c89    2017-08-07 10:17:31
C_ID_ffe5cb03ac    2017-08-26 10:14:50
C_ID_ffe609698f    2017-12-05 17:03:15
C_ID_ffe670105f    2017-01-02 07:36:17
C_ID_ffe688fd68    2017-01-24 10:21:51
C_ID_ffe6a84c59    2017-03-11 18:42:06
C_ID_ffe6dcc805    2017-10-14 13:57:17
C_ID_ffe703f745    2017-10-28 16:09:06
C_ID_ffe71ec373    2017-01-04 13:19:32
C_ID_ffe754d10c    2017-08-24 12:05:12
C_ID_ffe7871f38    2017-12-28 08:04:18
C_ID_ffe791f795    2017-01-05 19:33:50
C_ID_ffe7a0256d    2017-01-25 08:38:22
C_ID_ffe80c5734    2017-05-06 19:23:10
C_ID_ffe83ac1ec    2017-01-14 13:44:17
C_ID_ffe85078c8    2017-03-20 17:46:56
C_ID_ffe8541af1    2017-09-26 19:26:39
C_ID_ffe85833bd    2017-01-11 09:58:58
C_ID_ffe8645e27    2017-02-23 14:17:02
C_ID_ffe8bf9ef2    2017-04-27 12:55:51
C_ID_ffe8e34523    2017-01-04 09:02:43
C_ID_ffe9091205    2017-01-02 20:42:26
C_ID_ffe9338443    2017-01-11 16:33:30
C_ID_ffe969e56f    2017-09-17 21:50:41
C_ID_ffe97acefc    2017-10-19 00:00:00
C_ID_ffe98a4674    2017-06-06 13:54:04
C_ID_ffe9944d60    2017-01-10 15:04:01
C_ID_ffea783298    2017-05-07 11:32:49
C_ID_ffea95ca66    2017-01-06 16:42:22
C_ID_ffeaa35463    2017-04-12 11:27:24
C_ID_ffeacaa081    2017-01-04 14:30:42
C_ID_ffeb02d2bb    2017-01-04 12:21:09
C_ID_ffeb0898b5    2017-05-31 14:18:03
C_ID_ffeb258d93    2017-01-02 07:23:01
C_ID_ffeb978d3b    2017-09-17 21:58:30
C_ID_ffebe44c6d    2017-06-06 14:15:02
C_ID_ffebf84f15    2017-11-13 19:06:08
C_ID_ffec0ead94    2017-02-01 17:14:06
C_ID_ffec3e797c    2017-04-14 20:31:52
C_ID_ffec483ae9    2017-01-05 12:53:25
C_ID_ffec615a26    2017-01-01 12:07:22
C_ID_ffec69c581    2017-09-17 23:54:43
C_ID_ffec7d3b3b    2017-07-27 11:12:50
C_ID_ffec95782a    2017-10-19 18:41:28
C_ID_ffecac6ec9    2017-01-12 14:37:38
C_ID_ffecc9625f    2017-05-29 09:59:02
C_ID_ffeccd43c9    2017-04-06 16:50:49
C_ID_ffece651ab    2017-01-21 10:41:19
C_ID_ffed5c1f3e    2017-09-21 18:07:16
C_ID_ffedb3bbdb    2017-08-17 18:54:36
C_ID_ffee45f941    2017-09-15 21:04:39
C_ID_ffeec704aa    2017-01-09 15:13:40
C_ID_ffeec72833    2017-01-04 13:02:56
C_ID_ffef6a5157    2017-01-17 11:01:09
C_ID_ffef724ee2    2017-07-21 15:56:03
C_ID_ffefdb10d6    2017-01-12 18:28:01
C_ID_ffefee0a04    2017-08-09 17:37:55
C_ID_fff01c7ee1    2017-11-06 15:22:38
C_ID_fff04976bb    2017-01-02 11:20:27
C_ID_fff04aa1f5    2017-04-11 09:30:12
C_ID_fff0688a04    2017-01-03 13:51:36
C_ID_fff06f2aad    2017-01-09 15:49:02
C_ID_fff0ec3a73    2017-02-03 14:34:04
C_ID_fff0f2f9ce    2017-01-02 14:06:40
C_ID_fff115ef2e    2017-09-06 16:03:39
C_ID_fff12bcae2    2017-01-21 17:16:55
C_ID_fff13e9843    2017-02-15 17:37:08
C_ID_fff172a7fa    2017-02-25 13:09:34
C_ID_fff174b839    2017-03-11 12:07:38
C_ID_fff17acd27    2017-01-18 18:22:32
C_ID_fff184faf3    2017-01-04 11:11:46
C_ID_fff1d3ae5f    2017-01-02 10:04:29
C_ID_fff201065c    2017-01-20 21:35:26
C_ID_fff21f3bbc    2017-01-06 12:14:08
C_ID_fff2946cca    2017-01-02 20:51:51
C_ID_fff2ef437b    2017-03-24 15:37:15
C_ID_fff33122b1    2017-06-06 10:16:25
C_ID_fff34656e5    2017-05-31 14:22:03
C_ID_fff38f8134    2017-07-25 15:45:01
C_ID_fff3b3d49e    2017-07-29 10:07:31
C_ID_fff3b465e4    2017-02-22 17:04:27
C_ID_fff3bcdb73    2017-06-24 14:43:45
C_ID_fff3c52f3c    2017-06-06 16:15:10
C_ID_fff47dea33    2017-02-28 11:17:16
C_ID_fff4c4312c    2017-09-10 11:30:38
C_ID_fff4ec311a    2017-01-02 19:49:58
C_ID_fff4ed08c5    2017-02-02 23:03:52
C_ID_fff50bff5e    2017-09-04 14:48:38
C_ID_fff50ce0e0    2017-11-18 00:00:00
C_ID_fff56b7768    2017-04-22 13:39:33
C_ID_fff5be9c03    2017-04-10 12:30:26
C_ID_fff6341ea6    2017-03-30 22:07:13
C_ID_fff678cf7b    2017-12-20 20:22:30
C_ID_fff690bccc    2017-01-03 21:00:08
C_ID_fff6974041    2017-09-07 14:46:00
C_ID_fff6b4456b    2017-01-13 14:00:07
C_ID_fff6bf5305    2017-11-12 15:38:50
C_ID_fff6e4fefb    2017-01-08 22:30:56
C_ID_fff7031631    2017-01-13 11:26:24
C_ID_fff74c6e55    2017-07-05 13:35:17
C_ID_fff7714bc3    2017-01-20 11:09:15
C_ID_fff796a3f9    2017-11-11 17:24:30
C_ID_fff82c2722    2017-01-01 01:59:06
C_ID_fff845b82f    2017-11-17 20:34:50
C_ID_fff8874bc1    2017-05-04 06:54:30
C_ID_fff8d507b4    2017-01-05 10:00:14
C_ID_fff8e0d7da    2017-01-09 18:51:52
C_ID_fff91cdd28    2017-01-19 10:45:56
C_ID_fff96876e0    2017-07-30 10:29:37
C_ID_fff9e6b8e4    2017-07-15 12:58:55
C_ID_fffa2280c9    2017-01-01 18:09:59
C_ID_fffa2ced7d    2017-06-16 13:12:59
C_ID_fffa362304    2017-11-09 17:21:18
C_ID_fffa99d1da    2017-01-02 15:02:15
C_ID_fffadd3551    2017-01-03 09:13:56
C_ID_fffaed41f0    2017-11-19 20:01:10
C_ID_fffb59b27a    2017-08-21 12:13:36
C_ID_fffb67f260    2017-12-09 14:14:54
C_ID_fffb79fb56    2017-01-03 19:00:42
C_ID_fffb9ea3f6    2017-07-18 11:29:59
C_ID_fffba72dc5    2017-10-19 20:01:44
C_ID_fffbdf036b    2017-01-30 19:18:57
C_ID_fffbee5c24    2017-03-20 18:53:58
C_ID_fffc96bf24    2017-01-01 09:33:51
C_ID_fffcb74f49    2017-06-20 10:14:26
C_ID_fffcf66e12    2017-01-08 07:47:31
C_ID_fffd070e0e    2017-01-31 16:15:14
C_ID_fffd1207a8    2017-01-01 21:12:59
C_ID_fffd24dcf3    2017-05-22 16:16:09
C_ID_fffd337484    2017-03-13 15:56:33
C_ID_fffd345048    2017-08-07 14:55:00
C_ID_fffd351e7f    2017-05-27 06:11:16
C_ID_fffd93c8bf    2017-10-06 05:30:54
C_ID_fffd943b91    2017-03-07 17:19:17
C_ID_fffdad8aa0    2017-10-19 20:55:57
C_ID_fffde15ab6    2017-06-24 20:00:18
C_ID_fffdf34798    2017-04-22 12:03:52
C_ID_fffe29a04a    2017-04-09 01:48:52
C_ID_fffe78b232    2017-01-04 12:56:10
C_ID_fffe866457    2017-04-01 10:59:00
C_ID_fffea6de74    2017-06-01 14:08:07
C_ID_fffeced303    2017-04-11 18:36:00
C_ID_fffeed3a89    2017-11-04 00:15:13
C_ID_ffff1d9928    2017-10-26 00:00:00
C_ID_ffff579d3a    2017-08-08 12:33:43
C_ID_ffff756266    2017-01-24 20:00:38
C_ID_ffff828181    2017-01-05 15:27:33
C_ID_fffffd5772    2017-08-21 18:56:01
Name: purchase_date, Length: 325540, dtype: object

In [ ]:
history.

In [88]:
history[history.card_id == 'C_ID_0001506ef0'].sort_values('purchase_date')[['authorized_flag', 'city_id', 'category_1', 'merchant_category_id', 'merchant_id', 'purchase_amount_new', 'purchase_date']]

,authorized_flag,city_id,category_1,merchant_category_id,merchant_id,purchase_amount_new,purchase_date
25106445,Y,137,N,528,M_ID_5b63dd8e8f,39.00,2017-01-14 16:16:01
25106437,Y,147,N,419,M_ID_9394291a35,12.00,2017-01-17 18:59:15
25106435,Y,137,N,356,M_ID_a7e436f34b,16.10,2017-02-04 10:55:33
25106425,Y,137,N,705,M_ID_44a56d9dde,51.46,2017-02-04 11:34:52
25106415,Y,137,N,705,M_ID_a091680880,20.42,2017-02-04 14:18:55
25106410,Y,137,N,68,M_ID_947464c61c,17.50,2017-02-04 14:20:33
25106448,Y,137,N,278,M_ID_00fad79ed7,79.00,2017-02-10 13:58:05
25106417,Y,137,N,705,M_ID_da35a6d13e,46.74,2017-03-02 21:27:57
25106432,Y,137,N,68,M_ID_947464c61c,31.00,2017-03-05 14:16:45
25106452,Y,137,N,178,M_ID_f34e54b60f,18.22,2017-03-17 15:24:54
25106460,Y,137,N,437,M_ID_72a942cf9d,45.74,2017-03-25 14:05:39
25106447,Y,137,N,705,M_ID_a091680880,33.83,2017-03-25 15:07:56
25106418,Y,137,N,356,M_ID_a7e436f34b,58.20,2017-03-28 15:20:11
25106422,Y,137,N,222,M_ID_360e8974cf,25.90,2017-03-29 15:28:44
25106427,Y,137,N,222,M_ID_f27cd7b5f3,26.90,2017-03-31 10:44:00
25106421,Y,137,N,705,M_ID_44a56d9dde,30.00,2017-05-20 10:45:18
25106453,N,137,N,560,M_ID_d1f8cc0632,4.27,2017-06-06 17:58:52
25106431,Y,137,N,560,M_ID_d1f8cc0632,4.27,2017-06-06 17:59:26
25106433,Y,137,N,705,M_ID_b1fc88154d,16.33,2017-06-07 08:02:25
25106405,Y,137,N,705,M_ID_b1fc88154d,15.00,2017-07-06 09:15:21
25106426,Y,137,N,705,M_ID_b1fc88154d,1002.00,2017-07-07 13:31:26
25106412,Y,137,N,367,M_ID_6e28ed46c0,7.50,2017-08-01 07:20:40
25106401,Y,137,N,705,M_ID_b1fc88154d,842.00,2017-08-08 12:53:29
25106428,Y,137,N,705,M_ID_b1fc88154d,750.00,2017-09-06 15:29:58
25106442,Y,137,N,68,M_ID_947464c61c,20.50,2017-09-16 14:54:57
25106419,Y,137,N,705,M_ID_b1fc88154d,850.00,2017-10-10 15:33:26
25106463,Y,137,N,705,M_ID_b1fc88154d,45.74,2017-10-19 10:59:52
25106407,Y,137,N,705,M_ID_b1fc88154d,15.00,2017-10-19 11:01:00
25106424,Y,137,N,705,M_ID_b1fc88154d,31.14,2017-11-09 16:31:01
25106459,Y,137,N,705,M_ID_b1fc88154d,850.00,2017-11-09 16:32:13
25106429,Y,137,N,367,M_ID_761043b791,104.90,2017-11-10 11:27:30
25106441,Y,137,N,557,M_ID_b2d92cbcdc,25.00,2017-11-11 00:00:00
25106440,Y,137,N,437,M_ID_72a942cf9d,58.26,2017-11-11 12:08:57
25106450,Y,137,N,437,M_ID_72a942cf9d,15.00,2017-11-11 12:10:13
25106464,Y,137,N,367,M_ID_450fa3a651,4.98,2017-11-27 13:27:26
25106444,Y,137,N,705,M_ID_44a56d9dde,17.25,2017-12-02 12:56:26
25106430,Y,137,N,705,M_ID_2bc44fb971,5.50,2017-12-06 16:18:22
25106423,Y,137,N,437,M_ID_8e693c40a6,5.99,2017-12-06 19:08:53
25106456,N,137,N,179,M_ID_223f70933b,4.70,2017-12-07 10:43:20
25106414,Y,137,N,179,M_ID_223f70933b,4.70,2017-12-07 10:44:33
25106443,Y,137,N,68,M_ID_387c114289,57.00,2017-12-09 09:17:30
25106457,Y,137,N,705,M_ID_44a56d9dde,22.94,2017-12-09 12:19:39
25106434,Y,137,N,367,M_ID_19799774fc,7.99,2017-12-09 12:35:09
25106408,Y,69,N,879,M_ID_00a6ca8a8a,27.50,2017-12-09 12:55:15
25106451,Y,69,N,879,M_ID_00a6ca8a8a,11.00,2017-12-09 12:58:00
25106420,Y,137,N,179,M_ID_223f70933b,4.70,2017-12-11 14:23:28
25106436,Y,137,N,705,M_ID_b1fc88154d,750.00,2017-12-11 15:09:23
25106449,Y,137,N,783,M_ID_a222524a94,68.00,2017-12-12 07:09:43
25106411,Y,137,N,87,M_ID_ade7bbdbd1,140.00,2017-12-15 14:29:11
25106402,Y,137,N,705,M_ID_44a56d9dde,72.02,2017-12-16 13:04:58
25106400,Y,137,N,422,M_ID_93aa47602a,110.00,2017-12-23 08:25:45
25106465,Y,137,N,437,M_ID_72a942cf9d,200.00,2017-12-23 12:25:24
25106409,Y,137,N,68,M_ID_947464c61c,70.00,2017-12-23 16:04:14
25106416,Y,137,N,437,M_ID_72a942cf9d,15.00,2018-01-06 12:36:31
25106446,Y,137,N,437,M_ID_72a942cf9d,46.21,2018-01-06 12:42:18
25106461,Y,137,N,68,M_ID_947464c61c,23.50,2018-01-06 13:11:42
25106403,Y,137,N,813,M_ID_947464c61c,31.50,2018-01-07 10:54:26
25106438,Y,137,N,705,M_ID_b1fc88154d,1100.00,2018-01-08 12:33:18
25106404,Y,137,N,309,M_ID_939b13210d,84.09,2018-01-17 12:59:34
25106462,Y,137,N,222,M_ID_360e8974cf,65.00,2018-01-30 12:57:27
25106413,Y,137,N,705,M_ID_44a56d9dde,38.25,2018-02-03 11:44:25
25106455,Y,137,N,705,M_ID_b1fc88154d,1491.00,2018-02-08 14:30:56
25106439,N,137,N,813,M_ID_947464c61c,25.50,2018-02-11 12:10:15
25106406,Y,137,N,813,M_ID_947464c61c,25.50,2018-02-11 12:10:40
25106458,N,137,N,705,M_ID_44a56d9dde,20.00,2018-02-17 12:33:27
25106454,Y,137,N,705,M_ID_44a56d9dde,20.00,2018-02-17 12:33:56

In [103]:
subcribe = history.groupby('merchant_id').purchase_amount_new.unique().apply(lambda v: len(v)) / history.groupby('merchant_id').purchase_amount_new.size()

In [122]:
subcribe[subcribe < 0.01]

merchant_id
M_ID_090e1af690    0.008161
M_ID_16e9bb33cb    0.005479
M_ID_25a246d8b1    0.006897
M_ID_26e3278f88    0.003886
M_ID_2711dfd360    0.008108
M_ID_27f1c9c0de    0.008611
M_ID_41c2f75c85    0.007215
M_ID_43db5e6574    0.002635
M_ID_445742726b    0.000905
M_ID_453711c584    0.006660
M_ID_57aa0d9583    0.003799
M_ID_57df19bf28    0.005967
M_ID_5a0a412718    0.004278
M_ID_60256cbdd2    0.008559
M_ID_607cc18061    0.008772
M_ID_6e4e6bbc25    0.003595
M_ID_7de6986c09    0.005571
M_ID_86be58d7e0    0.000864
M_ID_8da0d33c72    0.002642
M_ID_9a20e54a94    0.007117
M_ID_a1eac7067f    0.006061
M_ID_c349b8d945    0.006090
M_ID_c8e18df911    0.005507
M_ID_ddea79d8f2    0.003241
M_ID_e1861056cc    0.001564
M_ID_e466d7a610    0.005727
M_ID_e6b5829419    0.009091
M_ID_eaccd4f2f0    0.006667
M_ID_f35b1f6e8d    0.005714
M_ID_fc7d7969c3    0.000045
Name: purchase_amount_new, dtype: float64

In [123]:
history[history.merchant_id == 'M_ID_16e9bb33cb'].sort_values(['card_id', 'purchase_date'])[['card_id','authorized_flag', 'city_id', 'category_1', 'merchant_category_id', 'merchant_id', 'purchase_amount_new', 'purchase_date']]

,card_id,authorized_flag,city_id,category_1,merchant_category_id,merchant_id,purchase_amount_new,purchase_date
8070554,C_ID_00117f101b,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-22 00:02:06
8070553,C_ID_00117f101b,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-22 22:59:30
22490054,C_ID_00b122bf46,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-16 17:27:31
22490035,C_ID_00b122bf46,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-10 21:23:59
26332325,C_ID_05522abe11,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-16 15:23:23
26332369,C_ID_05522abe11,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-16 15:24:07
5359939,C_ID_061f6873a7,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-12 18:11:42
15203210,C_ID_074cda2e99,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-31 20:24:34
4170784,C_ID_0788186ac7,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-17 01:19:26
26295413,C_ID_0d26aba4df,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-20 23:47:31
26295386,C_ID_0d26aba4df,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-25 00:00:00
26295403,C_ID_0d26aba4df,N,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-08 19:44:29
26295393,C_ID_0d26aba4df,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-08 19:45:09
26295405,C_ID_0d26aba4df,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-12 20:20:35
20764046,C_ID_0d5edf8654,Y,64,N,454,M_ID_16e9bb33cb,5.0,2017-06-10 13:53:59
7432762,C_ID_0db2ffaf07,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-29 00:53:09
1511989,C_ID_0dcacdc729,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-14 19:45:35
8109526,C_ID_0fcbb003fe,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-20 17:47:17
15220338,C_ID_10c0e0806d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-26 22:02:34
16259918,C_ID_10f6cbbac3,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-24 02:17:47
16259908,C_ID_10f6cbbac3,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-24 02:19:18
16259887,C_ID_10f6cbbac3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-24 02:19:21
16259904,C_ID_10f6cbbac3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-21 21:26:42
198720,C_ID_111dffc298,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-10 14:43:06
2224941,C_ID_1222bcccc4,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-01-08 19:45:15
21294562,C_ID_1407f7911e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-11 22:40:07
21294547,C_ID_1407f7911e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-17 20:16:47
12031158,C_ID_145f8e173d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-23 21:38:20
16432614,C_ID_14989f1bef,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-09 02:06:10
16432615,C_ID_14989f1bef,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-29 19:06:16
4697909,C_ID_15cd012eab,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-10 19:31:31
22544242,C_ID_15ce83ce8c,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-17 23:14:35
22544226,C_ID_15ce83ce8c,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-17 23:15:13
21646066,C_ID_1847bdf1ad,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-08 20:42:29
3849769,C_ID_1874390d83,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-22 01:23:04
26395270,C_ID_18aea9a230,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-01-02 14:07:21
26395289,C_ID_18aea9a230,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-17 17:02:11
27297631,C_ID_193d53111c,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-15 16:20:02
16625463,C_ID_1c00714d29,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-11 20:35:46
6610266,C_ID_1c34398619,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-27 21:58:42
1695241,C_ID_1e0e282a75,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-24 15:30:34
13772660,C_ID_20a52cafa0,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-01-07 15:27:14
13772695,C_ID_20a52cafa0,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-01-12 21:37:07
13772603,C_ID_20a52cafa0,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-01 17:51:07
13772704,C_ID_20a52cafa0,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-08 22:06:33
13772690,C_ID_20a52cafa0,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-10 14:50:41
13772691,C_ID_20a52cafa0,N,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-02 16:57:46
23847667,C_ID_20a771a0c9,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-11 19:36:50
23847678,C_ID_20a771a0c9,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-16 20:59:47
23847639,C_ID_20a771a0c9,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-20 18:45:07
23847635,C_ID_20a771a0c9,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-21 15:50:02
11032527,C_ID_22b59c3e3d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-22 22:06:06
11032422,C_ID_22b59c3e3d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-22 12:34:14
11032476,C_ID_22b59c3e3d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-08 01:03:16
24244935,C_ID_2345bd8729,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-11 22:44:01
24244979,C_ID_2345bd8729,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-12 21:19:42
24244960,C_ID_2345bd8729,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-02 01:27:14
24244949,C_ID_2345bd8729,N,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-12 18:42:13
2664642,C_ID_24dd23d609,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-06 20:31:04
13824085,C_ID_2859b571e3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-04 20:55:14
13824147,C_ID_2859b571e3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-21 14:03:55
13824146,C_ID_2859b571e3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-27 15:27:56
17734235,C_ID_29466152f1,Y,64,N,454,M_ID_16e9bb33cb,5.0,2017-10-12 21:14:25
15031665,C_ID_2a21fdeda2,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-12 21:03:23
4287319,C_ID_2ae2bee3e7,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-17 18:33:58
9970986,C_ID_2e80e3799d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-15 17:57:10
18449024,C_ID_2ece42a3df,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-02 22:48:49
10307743,C_ID_302880b381,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-05 21:04:28
10307759,C_ID_302880b381,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-26 15:03:34
4140065,C_ID_30ad6f5a0c,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-03 13:28:06
18854822,C_ID_338924405f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-23 18:25:57
22111025,C_ID_33a2027659,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-28 21:59:27
22111079,C_ID_33a2027659,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-28 22:00:09
13588618,C_ID_367578f64b,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-13 17:14:26
12977481,C_ID_3882e6bc38,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-04 19:11:31
24238574,C_ID_3a2a4c7900,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-01-15 22:38:50
24238578,C_ID_3a2a4c7900,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-02 00:00:00
13822258,C_ID_3c3aa8eeed,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-21 16:58:40
17609350,C_ID_3da0bd0db6,Y,64,N,454,M_ID_16e9bb33cb,5.0,2017-10-02 20:57:43
27304894,C_ID_3e581fb61f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-28 17:43:31
15228018,C_ID_3e6377fe64,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-09 14:30:59
21967744,C_ID_3f4d097d36,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-10 19:34:36
19194288,C_ID_3fb4098f34,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-24 19:10:19
7924760,C_ID_420f5126a1,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-04 16:54:26
23238892,C_ID_42b14e73a1,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-24 19:22:50
23238900,C_ID_42b14e73a1,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-01 19:55:21
23815330,C_ID_44bbae1ad8,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-22 23:20:50
3908320,C_ID_45361ba0e7,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-22 16:30:19
3908408,C_ID_45361ba0e7,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-02 15:11:50
9980247,C_ID_46bd585b0a,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-09 20:24:17
223992,C_ID_477f3af39e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-05 20:46:36
223782,C_ID_477f3af39e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-21 22:54:06
223812,C_ID_477f3af39e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-16 00:47:52
223951,C_ID_477f3af39e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-14 15:58:54
5853751,C_ID_480d135571,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-02 21:12:16
5853672,C_ID_480d135571,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-02 21:13:22
5853686,C_ID_480d135571,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-26 18:02:31
11981598,C_ID_48a9a8ff3e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-21 20:13:40
11981595,C_ID_48a9a8ff3e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-18 20:51:52
20207518,C_ID_4a88c7acab,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-12 00:38:07
15856115,C_ID_4b0bd6dfb7,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-08 22:24:43
15856097,C_ID_4b0bd6dfb7,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-08 22:25:35
17357354,C_ID_4c3adde9e6,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-22 10:53:31
16287814,C_ID_4cd2b3e6df,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-15 00:00:00
10960145,C_ID_4d14302538,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-29 21:24:44
10253647,C_ID_4d7f1215d1,Y,64,N,454,M_ID_16e9bb33cb,5.0,2017-01-06 01:12:36
19779893,C_ID_4e2819d45d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-16 21:01:19
19779960,C_ID_4e2819d45d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-25 17:41:22
19780005,C_ID_4e2819d45d,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-11 23:02:30
19779989,C_ID_4e2819d45d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-11 23:03:52
1421740,C_ID_4e3af78db8,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-10 20:54:50
24708558,C_ID_4e48d1e3e7,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-08 21:09:45
1686958,C_ID_4e8518b317,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-03 23:34:53
1687075,C_ID_4e8518b317,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-05 01:20:51
26997884,C_ID_5100320604,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-05 20:23:31
20112045,C_ID_52214b3981,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-01 22:12:40
3534301,C_ID_530fa19da2,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-07 21:46:12
6960146,C_ID_54734b50c2,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-19 22:49:00
6959798,C_ID_54734b50c2,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-16 20:54:33
6959919,C_ID_54734b50c2,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-10 23:24:59
6960039,C_ID_54734b50c2,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-11 00:00:00
12547886,C_ID_5546e06eed,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-31 15:38:36
27596517,C_ID_55a06f71e5,Y,64,N,454,M_ID_16e9bb33cb,5.0,2017-09-03 23:42:40
5164184,C_ID_5f1c47662b,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-23 16:15:48
3507608,C_ID_5f338987a5,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-06 16:41:53
25114778,C_ID_5fe9b4e177,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-24 10:44:45
17926352,C_ID_601d045bd3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-08 18:06:48
17926349,C_ID_601d045bd3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-09 21:52:34
17926361,C_ID_601d045bd3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-27 09:36:48
9994100,C_ID_60de302215,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-28 12:29:03
2895723,C_ID_621bd02e89,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-27 19:17:00
2895498,C_ID_621bd02e89,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-28 22:50:57
2895732,C_ID_621bd02e89,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-02 01:34:31
2895689,C_ID_621bd02e89,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-16 20:57:59
27173880,C_ID_628a54feac,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-26 22:02:36
27173897,C_ID_628a54feac,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-30 15:42:31
27173886,C_ID_628a54feac,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-23 21:02:24
25255382,C_ID_62c0766489,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-26 23:07:37
25255289,C_ID_62c0766489,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-31 22:20:15
27076091,C_ID_650679f868,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-20 01:18:27
24710100,C_ID_65fa85f73e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-05 22:11:02
25499939,C_ID_67eded4b15,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-15 20:58:34
25499942,C_ID_67eded4b15,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-11 00:29:14
1093329,C_ID_68427f21bd,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-14 22:00:38
1093279,C_ID_68427f21bd,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-14 22:01:28
1093432,C_ID_68427f21bd,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-14 22:02:51
1093365,C_ID_68427f21bd,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-23 19:37:19
18754432,C_ID_6843b78c6f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-24 17:57:39
26040306,C_ID_685f29fa21,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-23 18:59:15
23497151,C_ID_6d5f9918b6,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-01-20 17:12:17
19935021,C_ID_7090df4dcd,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-23 20:33:55
433658,C_ID_70f5aa0d3b,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-08 18:12:06
433892,C_ID_70f5aa0d3b,N,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-25 11:32:49
15283823,C_ID_714ce9a36d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-18 16:12:08
15283578,C_ID_714ce9a36d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-05 22:45:33
15283687,C_ID_714ce9a36d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-03 20:19:35
15283555,C_ID_714ce9a36d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-30 21:39:50
15283667,C_ID_714ce9a36d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-04 00:43:19
15283618,C_ID_714ce9a36d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-02 23:25:08
15283651,C_ID_714ce9a36d,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-17 00:00:00
15283785,C_ID_714ce9a36d,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-19 00:00:00
15283657,C_ID_714ce9a36d,N,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-06 20:16:48
28284198,C_ID_72f3f3e6c9,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-07 15:04:24
11829880,C_ID_73e8d264d8,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-21 19:10:05
431019,C_ID_74394b668a,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-12 20:49:30
14792494,C_ID_755406d964,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-13 16:56:05
9754119,C_ID_770e9ebb97,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-09 23:29:09
18315600,C_ID_7afe52c465,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-06 17:50:41
18804729,C_ID_7b2d262db2,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-10 22:41:41
18804695,C_ID_7b2d262db2,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-17 01:13:25
11860964,C_ID_7ccf694823,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-31 01:26:37
16418092,C_ID_7d16d218e6,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-16 17:38:50
14781866,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-11 17:11:14
14781860,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-25 21:21:05
14781956,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-26 18:38:32
14781883,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-07 15:34:01
14781871,C_ID_7da0544485,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-20 21:18:45
14781937,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-20 21:19:33
14781967,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-28 12:28:32
14781851,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-28 15:51:44
14781886,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-12 18:16:46
14781768,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-14 17:52:06
14781879,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-28 17:36:07
14781837,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-18 19:26:53
14781863,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-01 02:23:22
14781796,C_ID_7da0544485,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-21 21:03:06
5292445,C_ID_8136c169d6,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-01 15:08:47
5292415,C_ID_8136c169d6,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-22 15:20:47
21098723,C_ID_81470cdaa7,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-08 03:31:22
6423083,C_ID_83bf9e262f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-01-26 21:55:06
6422842,C_ID_83bf9e262f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-03-14 04:04:58
6423101,C_ID_83bf9e262f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-14 17:16:38
6423146,C_ID_83bf9e262f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-14 18:23:32
6422944,C_ID_83bf9e262f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-02 16:18:06
21235261,C_ID_8509ea8699,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-22 22:58:51
21290915,C_ID_85372f1029,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-02 18:14:07
12687139,C_ID_8600ef0b83,N,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-16 21:02:34
21823941,C_ID_8851394b23,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-07 14:39:58
4364277,C_ID_89e1ef2545,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-22 15:45:57
4364197,C_ID_89e1ef2545,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-05 14:45:34
4364303,C_ID_89e1ef2545,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-13 18:23:55
4364210,C_ID_89e1ef2545,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-13 18:28:34
4364158,C_ID_89e1ef2545,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-13 18:29:04
4364264,C_ID_89e1ef2545,N,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-24 16:49:24
4364147,C_ID_89e1ef2545,N,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-24 16:50:41
4364290,C_ID_89e1ef2545,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-24 16:52:48
4364167,C_ID_89e1ef2545,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-24 11:31:23
1456535,C_ID_8cd02ac5c3,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-29 17:33:11
28817363,C_ID_8d7906a34c,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-14 19:27:35
28817368,C_ID_8d7906a34c,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-27 17:27:59
20198434,C_ID_91e860decf,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-20 21:34:27
20198445,C_ID_91e860decf,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-20 21:35:13
26872944,C_ID_92c2f9a067,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-06 23:49:20
9504177,C_ID_937214a686,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-14 17:19:51
7844408,C_ID_94e783b48d,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-10 23:01:50
7844346,C_ID_94e783b48d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-10 23:02:43
7844316,C_ID_94e783b48d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-22 19:02:04
7844359,C_ID_94e783b48d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-21 16:06:59
7844302,C_ID_94e783b48d,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-22 22:39:54
7844420,C_ID_94e783b48d,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-22 22:40:58
7844259,C_ID_94e783b48d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-28 19:29:17
7844381,C_ID_94e783b48d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-09 18:23:57
7844399,C_ID_94e783b48d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-20 23:45:48
23153224,C_ID_95d04b32be,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-22 01:26:45
933866,C_ID_979b93849c,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-25 23:00:36
10008844,C_ID_9ad9444925,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-07-20 21:23:57
21190380,C_ID_9cf0d2e16d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-26 14:00:42
20423296,C_ID_a35e3ad59f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-15 22:13:52
15760150,C_ID_a830b6c394,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-19 00:00:00
11638856,C_ID_aaf5a97071,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-12 13:23:02
27235382,C_ID_ac9b446f4d,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-04-21 19:44:38
17393922,C_ID_adc9cdf0f4,Y,64,N,454,M_ID_16e9bb33cb,5.0,2017-06-12 22:29:55
17445385,C_ID_b0e1378ea5,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-18 18:11:29
14416171,C_ID_b155ecd601,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-01 20:22:27
9188730,C_ID_b1fa20a029,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-05 22:58:55
9253240,C_ID_b23627aa2e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-17 20:21:24
9253273,C_ID_b23627aa2e,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-23 23:19:13
9253287,C_ID_b23627aa2e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-23 23:19:43
9253052,C_ID_b23627aa2e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-24 18:47:01
9253031,C_ID_b23627aa2e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-12 22:26:08
9253248,C_ID_b23627aa2e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-28 22:25:56
9253155,C_ID_b23627aa2e,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-29 21:57:36
9253172,C_ID_b23627aa2e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-29 21:58:14
9253126,C_ID_b23627aa2e,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-23 08:59:24
18303264,C_ID_b2ec3bdad0,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-28 21:27:05
18303309,C_ID_b2ec3bdad0,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-07 20:34:55
18303337,C_ID_b2ec3bdad0,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-07 20:35:32
18303370,C_ID_b2ec3bdad0,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-07 20:38:10
3339487,C_ID_b64bc4be56,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-01 18:40:18
20910260,C_ID_b64f36df8f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-05-21 22:16:08
20910289,C_ID_b64f36df8f,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-10-28 23:45:37
6015009,C_ID_b6b096c9ef,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-02-21 15:47:23
18968668,C_ID_b75ce39054,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-07 22:40:35
18968673,C_ID_b75ce39054,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-06-10 20:28:09
18968573,C_ID_b75ce39054,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-08-17 17:49:21
18968629,C_ID_b75ce39054,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-09-09 18:22:01
18968633,C_ID_b75ce39054,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-02 23:51:27
18968655,C_ID_b75ce39054,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-12-29 16:33:52
18968676,C_ID_b75ce39054,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-07 18:49:21
18968542,C_ID_b75ce39054,Y,64,N,454,M_ID_16e9bb33cb,8.0,2018-01-07 18:51:28
21225543,C_ID_b9b66139db,N,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-04 19:11:45
21225542,C_ID_b9b66139db,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-02-04 19:12:31
18827885,C_ID_b9c547ba41,Y,64,N,454,M_ID_16e9bb33cb,8.0,2017-11-01 00:18:38

In [113]:
history[history.card_id == 'C_ID_ed9619314b'].sort_values(['purchase_date'])

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id,purchase_amount_new
6202919,Y,C_ID_ed9619314b,33,N,0,A,367,M_ID_cff668d25e,-12,-0.729853,2017-01-04 16:47:29,1.0,15,16,11.35
6202840,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.724368,2017-01-05 19:33:06,1.0,15,1,15.00
6202895,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-06 09:26:03,1.0,15,1,20.00
6202842,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-06 15:22:55,1.0,15,1,20.00
6202896,Y,C_ID_ed9619314b,33,N,0,A,705,M_ID_6bb021a8cc,-12,-0.677350,2017-01-07 20:22:26,1.0,15,33,46.29
6202871,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.724368,2017-01-08 12:12:37,1.0,15,1,15.00
6202911,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.724368,2017-01-10 07:30:05,1.0,15,1,15.00
6202885,Y,C_ID_ed9619314b,229,N,0,A,178,M_ID_c549d7624a,-12,-0.719860,2017-01-10 21:41:16,1.0,15,29,18.00
6202926,Y,C_ID_ed9619314b,69,N,0,A,511,M_ID_00a6ca8a8a,-12,-0.724368,2017-01-10 22:18:28,1.0,9,7,15.00
6202915,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-11 10:51:40,1.0,15,1,20.00
6202938,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.724368,2017-01-14 13:49:01,1.0,15,1,15.00
6202942,Y,C_ID_ed9619314b,33,N,0,A,506,M_ID_02f5c90d0e,-12,-0.687553,2017-01-16 12:43:46,1.0,15,30,39.50
6202838,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.724368,2017-01-17 14:49:20,1.0,15,1,15.00
6202901,Y,C_ID_ed9619314b,33,N,0,A,705,M_ID_6bb021a8cc,-12,-0.695111,2017-01-18 12:46:15,1.0,15,33,34.47
6202927,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-19 07:30:28,1.0,15,1,20.00
6202854,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-20 14:48:37,1.0,15,1,20.00
6202912,Y,C_ID_ed9619314b,33,N,0,A,437,M_ID_3b27ae1251,-12,-0.700641,2017-01-21 16:48:53,1.0,15,15,30.79
6202921,Y,C_ID_ed9619314b,33,N,0,A,705,M_ID_6bb021a8cc,-12,-0.686892,2017-01-21 17:11:57,1.0,15,33,39.94
6202845,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-21 18:33:19,1.0,15,1,20.00
6202894,N,C_ID_ed9619314b,158,N,1,B,755,M_ID_8fadd601d2,-12,-0.724368,2017-01-24 13:58:57,1.0,15,8,15.00
6202873,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.724368,2017-01-24 14:01:05,1.0,15,1,15.00
6202932,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-25 09:20:52,1.0,15,1,20.00
6202834,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.724368,2017-01-26 11:15:18,1.0,15,1,15.00
6202875,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-28 10:47:39,1.0,15,1,20.00
6202872,Y,C_ID_ed9619314b,33,N,0,A,705,M_ID_6917105285,-12,-0.701528,2017-01-28 15:13:50,1.0,15,33,30.20
6202909,Y,C_ID_ed9619314b,33,N,0,A,544,M_ID_2e00fb98e6,-12,-0.698823,2017-01-28 15:22:55,1.0,15,29,32.00
6202836,Y,C_ID_ed9619314b,33,N,0,A,705,M_ID_6bb021a8cc,-12,-0.718403,2017-01-28 19:15:18,1.0,15,33,18.97
6202877,Y,C_ID_ed9619314b,69,N,0,A,511,M_ID_00a6ca8a8a,-12,-0.691310,2017-01-29 21:51:20,1.0,9,7,37.00
6202936,Y,C_ID_ed9619314b,33,N,0,A,278,M_ID_a5a45de536,-12,-0.652241,2017-01-30 21:33:38,1.0,15,37,63.00
6202918,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-12,-0.716855,2017-01-31 11:25:46,1.0,15,1,20.00
6202857,Y,C_ID_ed9619314b,229,N,0,A,560,M_ID_38c5a01ed5,-11,-0.616989,2017-02-02 18:29:43,1.0,15,34,86.46
6202943,Y,C_ID_ed9619314b,33,N,0,A,650,M_ID_1adf95ec62,-11,-0.726171,2017-02-02 18:41:23,1.0,15,29,13.80
6202862,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-11,-0.716855,2017-02-03 10:59:18,1.0,15,1,20.00
6202852,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-11,-0.716855,2017-02-03 19:07:33,1.0,15,1,20.00
6202916,Y,C_ID_ed9619314b,33,N,0,A,705,M_ID_6bb021a8cc,-11,-0.694570,2017-02-04 15:06:15,1.0,15,33,34.83
6202920,Y,C_ID_ed9619314b,33,N,0,A,437,M_ID_3b27ae1251,-11,-0.693489,2017-02-05 11:24:07,1.0,15,15,35.55
6202876,Y,C_ID_ed9619314b,33,N,0,A,705,M_ID_4e5adb2fdc,-11,-0.599122,2017-02-06 20:45:53,1.0,15,33,98.35
6202884,Y,C_ID_ed9619314b,33,N,0,A,557,M_ID_f6b58c51a5,-11,-0.671775,2017-02-11 17:04:25,1.0,15,29,50.00
6202869,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-11,-0.716855,2017-02-17 13:08:44,1.0,15,1,20.00
6202898,Y,C_ID_ed9619314b,33,N,0,A,367,M_ID_cff668d25e,-11,-0.735653,2017-02-18 08:57:05,1.0,15,16,7.49
6202867,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-11,-0.716855,2017-02-18 10:52:37,1.0,15,1,20.00
6202882,Y,C_ID_ed9619314b,33,N,0,A,795,M_ID_01977e2bb7,-11,-0.699123,2017-02-18 16:45:51,1.0,15,29,31.80
6202859,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-11,-0.716855,2017-02-24 14:02:45,1.0,15,1,20.00
6202849,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-10,-0.724368,2017-03-02 12:37:18,1.0,15,1,15.00
6202841,Y,C_ID_ed9619314b,33,N,0,A,178,M_ID_1dafc920f0,-10,-0.694315,2017-03-04 18:31:44,1.0,15,29,35.00
6202888,Y,C_ID_ed9619314b,33,N,0,A,705,M_ID_a56f1197c6,-10,-0.678192,2017-03-05 22:46:08,1.0,15,33,45.73
6202847,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-10,-0.716855,2017-03-08 16:06:45,1.0,15,1,20.00
6202907,Y,C_ID_ed9619314b,69,N,0,A,511,M_ID_00a6ca8a8a,-10,-0.686802,2017-03-08 21:46:38,1.0,9,7,40.00
6202902,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-10,-0.716855,2017-03-09 16:36:02,1.0,15,1,20.00
6202839,Y,C_ID_ed9619314b,69,N,0,A,511,M_ID_00a6ca8a8a,-10,-0.732633,2017-03-10 03:03:40,1.0,9,7,9.50
6202874,N,C_ID_ed9619314b,69,N,0,A,511,M_ID_00a6ca8a8a,-10,-0.719860,2017-03-13 01:29:40,1.0,9,7,18.00
6202865,Y,C_ID_ed9619314b,33,N,0,A,278,M_ID_a5a45de536,-10,-0.719860,2017-03-13 01:30:17,1.0,15,37,18.00
6202844,Y,C_ID_ed9619314b,33,N,0,A,842,M_ID_a31dc6fde8,-10,-0.691205,2017-03-13 05:44:54,1.0,15,37,37.07
6202937,Y,C_ID_ed9619314b,33,N,0,A,842,M_ID_a31dc6fde8,-10,-0.739395,2017-03-15 01:02:40,1.0,15,37,5.00
6202879,Y,C_ID_ed9619314b,33,N,0,A,842,M_ID_a31dc6fde8,-10,-0.712527,2017-03-15 02:42:51,1.0,15,37,22.88
6202890,Y,C_ID_ed9619314b,33,N,0,A,779,M_ID_c9d1f637a5,-10,-0.713849,2017-03-15 15:53:40,1.0,15,27,22.00
6202939,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-10,-0.716855,2017-03-17 11:06:03,1.0,15,1,20.00
6202906,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-10,-0.716855,2017-03-20 12:46:17,1.0,15,1,20.00
6202843,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-10,-0.724368,2017-03-24 22:11:05,1.0,15,1,15.00
6202928,Y,C_ID_ed9619314b,69,N,0,A,511,M_ID_00a6ca8a8a,-9,-0.700326,2017-04-03 23:27:52,1.0,9,7,31.00
6202899,N,C_ID_ed9619314b,158,N,0,A,755,M_ID_8fadd601d2,-9,-0.716855,2017-04-05 18:46:08,1.0,15,8,20.00
6202858,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-9,-0.716855,2017-04-05 18:47:05,1.0,15,1,20.00
6202917,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-9,-0.724368,2017-04-06 13:41:35,1.0,15,1,15.00
6202940,Y,C_ID_ed9619314b,33,N,0,A,419,M_ID_00086d4dd0,-9,-0.716855,2017-04-20 08:23:43,1.0,15,1,20.00
6202855,Y,C_ID_ed9619314b,33,N,0,A,703,M_ID_94cadd8c35,-8,-0.707088,2017-05-25 11:53:57,1.0,15,29,26.50
6202897,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-8,-0.716855,2017-05-26 16:30:42,1.0,15,21,20.00
6202853,Y,C_ID_ed9619314b,33,N,0,A,68,M_ID_72e2037b89,-7,-0.656779,2017-06-12 15:30:15,1.0,15,27,59.98
6202861,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-6,-0.701828,2017-07-08 10:57:50,1.0,15,21,30.00
6202835,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-6,-0.716855,2017-07-17 13:44:24,1.0,15,21,20.00
6202881,N,C_ID_ed9619314b,33,N,1,B,367,M_ID_0775466a4e,-6,-0.711971,2017-07-21 13:55:26,1.0,15,16,23.25
6202929,N,C_ID_ed9619314b,33,N,0,A,367,M_ID_0775466a4e,-6,-0.711971,2017-07-21 13:56:00,1.0,15,16,23.25
6202910,Y,C_ID_ed9619314b,33,N,0,A,367,M_ID_0775466a4e,-6,-0.711971,2017-07-21 13:56:22,1.0,15,16,23.25
6202923,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-6,-0.716855,2017-07-25 11:32:32,1.0,15,21,20.00
6202856,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-6,-0.709342,2017-07-29 14:59:41,1.0,15,21,25.00
6202850,Y,C_ID_ed9619314b,33,N,0,A,222,M_ID_2f5d78be9f,-5,-0.716855,2017-08-11 14:42:40,1.0,15,21,20.00
6202935,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-5,-0.716855,2017-08-11 17:12:58,1.0,15,21,20.00
6202870,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-5,-0.724368,2017-08-11 19:30:10,1.0,15,21,15.00
6202941,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-5,-0.701828,2017-08-18 15:56:32,1.0,15,21,30.00
6202891,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-5,-0.709342,2017-08-20 10:21:01,1.0,15,21,25.00
6202900,Y,C_ID_ed9619314b,33,N,0,A,222,M_ID_2f5d78be9f,-5,-0.660505,2017-08-21 15:37:18,1.0,15,21,57.50
6202837,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-5,-0.716855,2017-08-23 10:05:40,1.0,15,21,20.00
6202924,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-5,-0.716855,2017-08-26 18:39:34,1.0,15,21,20.00
6202846,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-5,-0.724368,2017-08-26 18:40:41,1.0,15,21,15.00
6202914,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-5,-0.709342,2017-08-28 11:17:20,1.0,15,21,25.00
6202925,Y,C_ID_ed9619314b,33,N,0,A,63,M_ID_b6259ef586,-4,-0.728891,2017-09-04 20:36:51,1.0,15,27,11.99
6202880,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-4,-0.724368,2017-09-06 14:04:40,1.0,15,21,15.00
6202864,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-4,-0.716855,2017-09-06 14:06:30,1.0,15,21,20.00
6202878,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-4,-0.716855,2017-09-11 22:54:34,1.0,15,21,20.00
6202944,N,C_ID_ed9619314b,158,N,0,A,755,M_ID_8fadd601d2,-4,-0.724368,2017-09-13 18:11:48,1.0,15,8,15.00
6202922,N,C_ID_ed9619314b,158,N,0,A,755,M_ID_8fadd601d2,-4,-0.724368,2017-09-13 18:12:41,1.0,15,8,15.00
6202883,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-4,-0.716855,2017-09-22 15:33:24,1.0,15,21,20.00
6202908,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-4,-0.724368,2017-09-25 15:16:51,1.0,15,21,15.00
6202904,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-4,-0.709342,2017-09-26 20:39:48,1.0,15,21,25.00
6202934,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-3,-0.716855,2017-10-05 12:29:21,1.0,15,21,20.00
6202905,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-3,-0.725871,2017-10-07 13:02:30,1.0,15,21,14.00
6202851,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-3,-0.701828,2017-10-18 10:04:56,1.0,15,21,30.00
6202868,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-3,-0.725871,2017-10-25 13:49:27,1.0,15,21,14.00
6202886,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-3,-0.724368,2017-10-26 20:20:00,1.0,15,21,15.00
6202887,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-2,-0.716855,2017-11-02 15:42:22,1.0,15,21,20.00
6202893,Y,C_ID_ed9619314b,33,N,0,A,367,M_ID_92c4790c2e,-2,-0.677019,2017-11-03 00:00:00,1.0,15,16,46.51
6202863,Y,C_ID_ed9619314b,33,N,0,A,703,M_ID_c94c4c189a,-2,-0.688905,2017-11-11 16:26:44,1.0,15,29,38.60
6202903,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-2,-0.724368,2017-11-13 19:51:38,1.0,15,21,15.00
6202848,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-2,-0.724368,2017-11-27 21:18:08,1.0,15,21,15.00
6202889,Y,C_ID_ed9619314b,33,N,0,A,367,M_ID_92c4790c2e,-1,-0.680791,2017-12-09 12:18:14,1.0,15,16,44.00
6202913,Y,C_ID_ed9619314b,33,N,0,A,367,M_ID_17f86bb6ca,-1,-0.730694,2017-12-09 14:28:10,1.0,15,16,10.79
6202860,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,-1,-0.716855,2017-12-26 16:56:33,1.0,15,21,20.00
6202930,N,C_ID_ed9619314b,33,N,0,A,367,M_ID_0775466a4e,0,-0.701708,2018-01-06 15:51:16,1.0,15,16,30.08
6202892,Y,C_ID_ed9619314b,33,N,0,A,367,M_ID_0775466a4e,0,-0.701708,2018-01-06 15:51:35,1.0,15,16,30.08
6202933,Y,C_ID_ed9619314b,33,N,0,A,367,M_ID_0775466a4e,0,-0.712692,2018-01-06 15:52:29,1.0,15,16,22.77
6202931,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,0,-0.716855,2018-01-17 11:58:28,1.0,15,21,20.00
6202866,Y,C_ID_ed9619314b,33,N,0,A,443,M_ID_00086d4dd0,0,-0.725871,2018-01-22 18:13:03,1.0,15,21,14.00

In [124]:
train[train.card_id == 'C_ID_0d26aba4df']

Empty DataFrame
Columns: [first_active_month, card_id, feature_1, feature_2, feature_3, target, target_new]
Index: []

In [114]:
train['target_new'] = 10**(train['target']*np.log10(2))

In [24]:
history[history.category_1 == 'Y']

,authorized_flag,card_id,city_id,category_1,installments,category_3,merchant_category_id,merchant_id,month_lag,purchase_amount,purchase_date,category_2,state_id,subsector_id
797,Y,C_ID_48fb13e70f,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.649837,2017-12-09 13:04:14,NaN,-1,29
800,Y,C_ID_48fb13e70f,-1,Y,1,B,839,M_ID_50076f761c,-5,-0.596793,2017-09-21 23:28:00,NaN,-1,29
802,Y,C_ID_48fb13e70f,-1,Y,4,C,302,M_ID_b9f9332438,-8,0.764910,2017-06-07 05:20:49,NaN,-1,22
845,N,C_ID_48fb13e70f,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.649837,2017-12-20 20:38:40,NaN,-1,29
853,Y,C_ID_48fb13e70f,-1,Y,2,C,637,M_ID_963ed874ee,-1,-0.085741,2018-01-21 22:14:21,NaN,-1,37
997,Y,C_ID_fc8e41b9cf,-1,Y,10,C,706,M_ID_23ddadf852,-1,0.786548,2018-01-23 16:15:49,NaN,-1,26
1362,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,-1,-0.671925,2017-12-20 13:25:23,NaN,-1,8
1388,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,0,-0.671925,2018-01-21 09:51:02,NaN,-1,8
1420,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,-4,-0.671925,2017-09-24 18:16:10,NaN,-1,8
1422,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,-2,-0.671925,2017-11-19 16:22:11,NaN,-1,8
1428,Y,C_ID_4bed29d75c,-1,Y,1,B,661,M_ID_9e84cda3b1,-3,-0.671925,2017-10-19 18:08:32,NaN,-1,8
1430,Y,C_ID_4bed29d75c,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.745405,2017-09-24 17:16:29,NaN,-1,8
1438,N,C_ID_4bed29d75c,-1,Y,1,B,755,M_ID_57df19bf28,-4,-0.745405,2017-09-24 17:15:59,NaN,-1,8
2327,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.732197,2017-11-30 20:35:47,NaN,-1,29
2338,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.737907,2017-11-29 00:56:26,NaN,-1,29
2372,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733023,2017-12-01 22:03:29,NaN,-1,29
2382,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733925,2017-12-01 13:16:07,NaN,-1,29
2385,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.737877,2017-12-06 00:59:28,NaN,-1,29
2388,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,-4,-0.680791,2017-10-05 00:22:36,NaN,-1,29
2396,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.709176,2018-02-03 11:35:17,NaN,-1,29
2398,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.738268,2017-12-08 07:09:21,NaN,-1,29
2413,N,C_ID_058b254a5b,-1,Y,4,C,879,M_ID_9139332ccc,-7,-0.521660,2017-07-27 21:09:03,NaN,-1,29
2424,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733865,2017-12-11 07:04:43,NaN,-1,29
2444,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.729913,2017-12-01 21:23:42,NaN,-1,29
2448,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,-4,-0.679288,2017-10-25 01:26:07,NaN,-1,29
2454,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-04 14:54:14,NaN,-1,29
2483,Y,C_ID_058b254a5b,-1,Y,5,C,879,M_ID_9139332ccc,-3,-0.542187,2017-11-20 16:45:49,NaN,-1,29
2487,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,0,-0.685299,2018-02-09 22:48:36,NaN,-1,29
2491,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-04 14:54:56,NaN,-1,29
2493,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.738087,2017-12-02 21:39:00,NaN,-1,29
2503,N,C_ID_058b254a5b,-1,Y,10,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:26:26,NaN,-1,29
2511,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.710619,2017-12-01 21:48:05,NaN,-1,29
2520,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.710619,2017-12-04 12:40:44,NaN,-1,29
2521,N,C_ID_058b254a5b,-1,Y,4,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:24:40,NaN,-1,29
2522,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.692211,2017-11-26 03:14:09,NaN,-1,29
2524,Y,C_ID_058b254a5b,-1,Y,5,C,879,M_ID_9139332ccc,-3,-0.501405,2017-11-12 17:55:24,NaN,-1,29
2536,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.726457,2017-12-11 08:02:40,NaN,-1,29
2560,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.735037,2017-12-05 18:29:33,NaN,-1,29
2565,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.738268,2017-11-28 23:12:46,NaN,-1,29
2570,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733669,2017-12-08 18:58:08,NaN,-1,29
2571,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733730,2017-12-05 21:47:29,NaN,-1,29
2572,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.738268,2017-11-29 01:09:51,NaN,-1,29
2585,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.731731,2017-12-14 23:41:26,NaN,-1,29
2598,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,-4,-0.719860,2017-10-25 01:29:13,NaN,-1,29
2618,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-23 09:36:39,NaN,-1,29
2621,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.735999,2017-11-26 02:32:09,NaN,-1,29
2636,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.737276,2017-12-06 11:23:01,NaN,-1,29
2644,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.739274,2017-11-27 00:02:44,NaN,-1,29
2649,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-03 18:11:21,NaN,-1,29
2650,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-28 14:44:32,NaN,-1,29
2652,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.738087,2017-12-03 19:22:06,NaN,-1,29
2655,N,C_ID_058b254a5b,-1,Y,12,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:27:02,NaN,-1,29
2661,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.667478,2018-01-23 09:38:35,NaN,-1,29
2662,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.667463,2018-01-23 09:41:34,NaN,-1,29
2677,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.727779,2017-12-02 22:03:14,NaN,-1,29
2699,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.740897,2017-11-26 02:31:49,NaN,-1,29
2702,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733008,2017-12-11 07:03:20,NaN,-1,29
2703,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.717426,2018-01-28 14:49:07,NaN,-1,29
2706,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.738268,2017-12-08 07:18:51,NaN,-1,29
2714,Y,C_ID_058b254a5b,-1,Y,4,C,879,M_ID_9139332ccc,-7,-0.242017,2017-07-16 21:46:22,NaN,-1,29
2717,Y,C_ID_058b254a5b,-1,Y,2,C,879,M_ID_9139332ccc,-2,-0.690108,2017-12-07 23:43:18,NaN,-1,29
2722,N,C_ID_058b254a5b,-1,Y,10,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:26:15,NaN,-1,29
2734,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.733669,2017-12-08 19:27:00,NaN,-1,29
2749,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.740897,2018-01-28 14:47:39,NaN,-1,29
2750,N,C_ID_058b254a5b,-1,Y,6,C,879,M_ID_9139332ccc,-6,-0.521660,2017-08-09 23:25:33,NaN,-1,29
2762,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.736585,2017-12-02 21:42:53,NaN,-1,29
2765,Y,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.737817,2017-11-27 19:55:00,NaN,-1,29
2769,N,C_ID_058b254a5b,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.726517,2018-02-14 05:19:57,NaN,-1,29
2779,Y,C_ID_058b254a5b,-1,Y,2,C,879,M_ID_9139332ccc,0,-0.401148,2018-02-16 12:30:30,NaN,-1,29
2794,Y,C_ID_058b254a5b,-1,Y,1,B,879,M_ID_f28abf15c8,0,-0.684923,2018-02-09 22:46:41,NaN,-1,29
2830,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-01 13:33:34,NaN,-1,22
2847,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-2,-0.733399,2017-06-27 13:12:23,NaN,-1,22
2853,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.501991,2017-08-22 10:12:57,NaN,-1,22
2855,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-1,-0.733399,2017-07-18 13:16:42,NaN,-1,22
2861,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-5,-0.716735,2017-03-27 20:13:44,NaN,-1,22
2885,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-15 13:14:54,NaN,-1,22
2914,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-5,-0.742400,2017-03-27 20:10:19,NaN,-1,22
2926,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-29 16:14:58,NaN,-1,22
2946,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-1,-0.733399,2017-07-11 13:14:09,NaN,-1,22
2951,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-1,-0.733399,2017-07-25 14:52:53,NaN,-1,22
2965,Y,C_ID_a9af70f52d,-1,Y,1,B,879,M_ID_00a6ca8a8a,-4,-0.522637,2017-04-10 18:24:13,NaN,-1,29
2970,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-22 13:12:00,NaN,-1,22
2989,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,-1,-0.733399,2017-07-04 13:05:49,NaN,-1,22
3030,Y,C_ID_a9af70f52d,-1,Y,1,B,574,M_ID_6f274b9340,0,-0.733399,2017-08-08 13:10:42,NaN,-1,22
3935,N,C_ID_76ac7d7a48,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.743918,2017-12-08 22:02:10,NaN,-1,29
3958,N,C_ID_76ac7d7a48,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.743918,2017-12-08 22:00:25,NaN,-1,29
3968,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-5,-0.740897,2017-09-13 22:27:24,NaN,-1,29
3983,Y,C_ID_b45d4d37b1,-1,Y,2,C,665,M_ID_076cd8a829,-3,-0.177553,2017-11-06 19:24:53,NaN,-1,3
3984,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.736179,2018-02-06 18:14:14,NaN,-1,29
3987,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-4,0.514117,2017-10-26 19:39:40,NaN,-1,3
3988,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-4,-0.707073,2017-10-04 12:50:03,NaN,-1,29
3999,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-2,0.175420,2017-12-07 17:46:41,NaN,-1,3
4006,Y,C_ID_b45d4d37b1,-1,Y,6,C,491,M_ID_79692349d6,-6,2.925226,2017-08-25 15:34:05,NaN,-1,3
4012,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.738268,2018-02-19 17:53:46,NaN,-1,29
4013,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.734616,2018-02-17 08:43:44,NaN,-1,29
4035,N,C_ID_b45d4d37b1,-1,Y,3,C,550,M_ID_09d7a200d1,-2,1.005183,2017-12-14 16:45:52,NaN,-1,3
4037,N,C_ID_b45d4d37b1,-1,Y,3,C,550,M_ID_09d7a200d1,-2,1.005183,2017-12-15 02:46:35,NaN,-1,3
4043,Y,C_ID_b45d4d37b1,-1,Y,1,B,771,M_ID_eb21569741,-5,-0.496716,2017-09-19 00:01:28,NaN,-1,31
4055,N,C_ID_b45d4d37b1,-1,Y,6,C,550,M_ID_09d7a200d1,-6,1.970757,2017-08-28 12:09:44,NaN,-1,3
4064,Y,C_ID_b45d4d37b1,-1,Y,1,B,511,M_ID_28f1b3a0e7,-4,-0.548573,2017-10-09 18:33:39,NaN,-1,7
4082,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-4,-0.731971,2017-10-24 13:58:54,NaN,-1,29
4084,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.735322,2018-02-06 08:34:29,NaN,-1,29
4096,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-3,-0.204751,2017-11-05 02:16:58,NaN,-1,3
4099,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-5,-0.735488,2017-09-14 02:09:21,NaN,-1,29
4107,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-4,0.829373,2017-10-26 20:08:27,NaN,-1,3
4111,N,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-2,0.514117,2017-12-14 20:34:27,NaN,-1,3
4112,Y,C_ID_b45d4d37b1,-1,Y,3,C,491,M_ID_79692349d6,0,0.409157,2018-02-08 15:57:40,NaN,-1,3
4115,Y,C_ID_b45d4d37b1,-1,Y,4,C,665,M_ID_076cd8a829,-5,0.452058,2017-09-06 19:20:16,NaN,-1,3
4121,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.723812,2018-02-16 05:19:32,NaN,-1,29
4124,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.735322,2018-02-06 08:48:16,NaN,-1,29
4126,N,C_ID_b45d4d37b1,-1,Y,6,C,550,M_ID_09d7a200d1,-6,1.970757,2017-08-28 12:09:30,NaN,-1,3
4131,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.728485,2018-02-07 08:36:05,NaN,-1,29
4137,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.736179,2018-02-06 18:27:09,NaN,-1,29
4170,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_9139332ccc,0,-0.246194,2018-02-08 17:02:08,NaN,-1,29
4182,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.737712,2018-02-03 08:54:29,NaN,-1,29
4185,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_00a6ca8a8a,-3,-0.656749,2017-11-07 13:22:40,NaN,-1,29
4187,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.735352,2018-02-05 14:02:33,NaN,-1,29
4190,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.740897,2018-02-16 22:48:11,NaN,-1,29
4192,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-5,-0.726772,2017-09-13 22:41:26,NaN,-1,29
4193,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.735503,2018-01-26 13:44:13,NaN,-1,29
4195,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.297540,2017-12-13 18:19:04,NaN,-1,29
4212,Y,C_ID_b45d4d37b1,-1,Y,3,C,491,M_ID_79692349d6,0,3.253315,2018-02-08 12:13:13,NaN,-1,3
4217,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-3,-0.730859,2017-11-14 17:56:45,NaN,-1,29
4237,Y,C_ID_b45d4d37b1,-1,Y,2,C,511,M_ID_32e6648d9b,-1,0.771611,2018-01-05 13:22:03,NaN,-1,7
4238,Y,C_ID_b45d4d37b1,-1,Y,2,C,491,M_ID_79692349d6,-3,-0.277029,2017-11-05 01:19:55,NaN,-1,3
4244,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.730394,2018-01-28 20:42:04,NaN,-1,29
4253,Y,C_ID_b45d4d37b1,-1,Y,3,C,550,M_ID_09d7a200d1,-4,1.005183,2017-10-26 20:33:33,NaN,-1,3
4254,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.735683,2018-01-31 13:51:58,NaN,-1,29
4277,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.297540,2017-12-18 14:58:08,NaN,-1,29
4281,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.737456,2018-02-17 08:52:40,NaN,-1,29
4288,Y,C_ID_b45d4d37b1,-1,Y,1,B,771,M_ID_eb21569741,-5,-0.644412,2017-09-13 21:13:41,NaN,-1,31
4298,Y,C_ID_b45d4d37b1,-1,Y,1,B,661,M_ID_fc7d7969c3,0,-0.717005,2018-02-11 13:57:59,NaN,-1,8
4317,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.736705,2018-02-03 11:48:05,NaN,-1,29
4318,Y,C_ID_b45d4d37b1,-1,Y,2,C,550,M_ID_09d7a200d1,-2,0.061218,2017-12-07 17:32:13,NaN,-1,3
4327,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.737111,2018-02-17 12:07:05,NaN,-1,29
4333,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.728590,2018-02-07 15:17:44,NaN,-1,29
4334,Y,C_ID_b45d4d37b1,-1,Y,2,C,665,M_ID_076cd8a829,-3,-0.177553,2017-11-06 19:39:57,NaN,-1,3
4339,Y,C_ID_b45d4d37b1,-1,Y,2,C,879,M_ID_9139332ccc,-5,-0.238351,2017-09-13 12:38:50,NaN,-1,29
4364,Y,C_ID_b45d4d37b1,-1,Y,2,C,879,M_ID_9139332ccc,-2,0.188478,2017-12-12 22:24:39,NaN,-1,29
4375,Y,C_ID_b45d4d37b1,-1,Y,1,B,839,M_ID_e5374dabc0,-1,-0.731686,2018-01-31 14:29:09,NaN,-1,29
4378,Y,C_ID_b45d4d37b1,-1,Y,1,B,879,M_ID_9139332ccc,-5,-0.339088,2017-09-17 12:08:30,NaN,-1,29
5451,N,C_ID_3917d75318,-1,Y,1,B,879,M_ID_b9dcf28cb9,-2,-0.468917,2017-12-01 21:14:05,NaN,-1,29
6470,Y,C_ID_ad99f08d4c,-1,Y,5,C,879,M_ID_00a6ca8a8a,-4,0.632135,2017-10-27 11:34:58,NaN,-1,29
6481,Y,C_ID_ad99f08d4c,-1,Y,5,C,879,M_ID_00a6ca8a8a,-4,0.632135,2017-10-27 12:00:41,NaN,-1,29
6573,Y,C_ID_ad99f08d4c,-1,Y,5,C,879,M_ID_00a6ca8a8a,-4,0.632135,2017-10-27 11:30:39,NaN,-1,29
6603,Y,C_ID_e5f5fcf6e7,-1,Y,4,C,665,M_ID_076cd8a829,-3,1.329215,2017-11-16 10:54:27,NaN,-1,3
6606,Y,C_ID_e5f5fcf6e7,-1,Y,1,B,550,M_ID_09d7a200d1,-2,-0.599648,2017-12-06 15:56:50,NaN,-1,3
6616,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,550,M_ID_09d7a200d1,-3,1.434671,2017-11-08 14:31:23,NaN,-1,3
6636,Y,C_ID_e5f5fcf6e7,-1,Y,3,C,550,M_ID_09d7a200d1,-2,-0.231498,2017-12-06 11:54:42,NaN,-1,3
6646,N,C_ID_e5f5fcf6e7,-1,Y,6,C,690,M_ID_3111c6df35,-6,2.201279,2017-08-26 16:35:41,NaN,-1,1
6654,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,-0.115674,2017-08-24 15:02:31,NaN,-1,29
6673,N,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,-0.553907,2017-08-26 16:35:38,NaN,-1,29
6710,Y,C_ID_e5f5fcf6e7,-1,Y,4,C,665,M_ID_076cd8a829,-8,0.725796,2017-06-03 12:12:30,NaN,-1,3
6730,Y,C_ID_e5f5fcf6e7,-1,Y,4,C,665,M_ID_076cd8a829,-9,0.148702,2017-05-02 12:44:49,NaN,-1,3
6750,N,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,-0.553907,2017-08-26 16:35:39,NaN,-1,29
6752,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,-0.553907,2017-08-26 16:50:48,NaN,-1,29
6784,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,690,M_ID_3111c6df35,-6,2.201279,2017-08-26 16:50:50,NaN,-1,1
6815,Y,C_ID_e5f5fcf6e7,-1,Y,6,C,544,M_ID_3111c6df35,-6,2.978615,2017-08-24 15:02:32,NaN,-1,29
6929,N,C_ID_72b66c75ad,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.745405,2017-12-19 11:26:15,NaN,-1,29
6961,N,C_ID_72b66c75ad,-1,Y,1,B,839,M_ID_e5374dabc0,-2,-0.742400,2017-12-19 11:26:12,NaN,-1,29
7084,Y,C_ID_190bd090c9,-1,Y,1,B,755,M_ID_445742726b,-10,-0.716855,2017-02-21 06:20:45,NaN,-1,8
7099,Y,C_ID_190bd090c9,-1,Y,1,B,755,M_ID_445742726b,-9,-0.716855,2017-03-12 20:46:53,NaN,-1,8
7675,Y,C_ID_536bff298a,-1,Y,1,B,511,M_ID_9139332ccc,-11,-0.559076,2017-03-27 10:41:11,NaN,-1,7
7683,N,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-10,-0.584772,2017-04-27 23:59:19,NaN,-1,29
7695,N,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-10,-0.607327,2017-04-26 00:04:49,NaN,-1,29
7696,N,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.401298,2017-12-04 12:00:22,NaN,-1,29
7698,N,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-10,-0.584772,2017-04-26 12:58:52,NaN,-1,29
7705,Y,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-1,-0.659904,2018-01-31 23:26:37,NaN,-1,29
7707,Y,C_ID_536bff298a,-1,Y,1,B,755,M_ID_86be58d7e0,-3,-0.686802,2017-11-29 15:06:37,NaN,-1,8
7708,Y,C_ID_536bff298a,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.641737,2017-10-30 05:14:38,NaN,-1,29
7709,Y,C_ID_536bff298a,-1,Y,2,C,879,M_ID_9139332ccc,-2,-0.385430,2017-12-04 12:12:31,NaN,-1,29
7712,N,C_ID_536bff298a,-1,Y,1,B,511,M_ID_9139332ccc,-11,-0.559076,2017-03-27 00:56:46,NaN,-1,7
9410,Y,C_ID_a1b71153bd,-1,Y,1,B,690,M_ID_3111c6df35,-2,-0.371260,2017-11-10 18:58:00,NaN,-1,1
9421,Y,C_ID_a1b71153bd,-1,Y,2,C,834,M_ID_29ec8d2ab8,-3,-0.598145,2017-10-24 18:39:08,NaN,-1,27
9424,Y,C_ID_a1b71153bd,-1,Y,2,C,690,M_ID_3111c6df35,-4,-0.596658,2017-09-11 20:47:07,NaN,-1,1
9426,Y,C_ID_a1b71153bd,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.612000,2017-09-11 19:39:33,NaN,-1,29
9548,N,C_ID_d6f97e5780,-1,Y,1,B,839,M_ID_e5374dabc0,0,-0.740897,2018-02-07 17:18:45,NaN,-1,29
9642,N,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-8,-0.640520,2017-06-12 20:46:21,NaN,-1,16
9644,Y,C_ID_3df86e0089,-1,Y,1,B,884,M_ID_9dbbaabb0a,-10,-0.584802,2017-04-13 14:30:04,NaN,-1,27
9645,Y,C_ID_3df86e0089,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.627026,2017-12-04 14:38:35,NaN,-1,29
9646,Y,C_ID_3df86e0089,-1,Y,1,B,683,M_ID_94eea62513,-3,-0.612931,2017-11-13 14:26:51,NaN,-1,34
9647,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_7bb972553c,-10,-0.578010,2017-04-02 13:05:48,NaN,-1,16
9649,Y,C_ID_3df86e0089,-1,Y,1,B,561,M_ID_4d3d928d6f,-6,-0.686952,2017-08-28 13:45:36,NaN,-1,7
9650,N,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-8,-0.640520,2017-06-12 20:46:22,NaN,-1,16
9651,Y,C_ID_3df86e0089,-1,Y,1,B,705,M_ID_2105757cda,-12,-0.411531,2017-02-13 15:40:57,NaN,-1,33
9652,N,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-12,-0.178996,2017-02-10 12:11:00,NaN,-1,16
9653,N,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-12,-0.178996,2017-02-10 12:10:17,NaN,-1,16
9655,Y,C_ID_3df86e0089,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.521525,2017-10-09 16:00:29,NaN,-1,29
9656,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_7bb972553c,-12,-0.595501,2017-02-27 12:55:21,NaN,-1,16
9659,Y,C_ID_3df86e0089,-1,Y,1,B,561,M_ID_4d3d928d6f,-12,-0.686952,2017-02-26 18:15:33,NaN,-1,7
9660,Y,C_ID_3df86e0089,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.476461,2017-10-09 16:08:46,NaN,-1,29
9661,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-11,-0.467760,2017-03-10 15:24:13,NaN,-1,16
9662,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_7bb972553c,-2,-0.239718,2017-12-13 13:20:10,NaN,-1,16
9663,Y,C_ID_3df86e0089,-1,Y,1,B,561,M_ID_4d3d928d6f,-1,-0.686952,2018-01-28 07:55:53,NaN,-1,7
9664,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_7bb972553c,-8,-0.652421,2017-06-13 12:52:39,NaN,-1,16
9667,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_2a95494c5a,-11,-0.591834,2017-03-06 15:26:44,NaN,-1,16
9668,Y,C_ID_3df86e0089,-1,Y,1,B,879,M_ID_9139332ccc,0,-0.636012,2018-02-22 13:20:42,NaN,-1,29
9669,Y,C_ID_3df86e0089,-1,Y,1,B,690,M_ID_c9855bf3e3,-11,-0.617680,2017-03-29 14:56:29,NaN,-1,1
9670,Y,C_ID_3df86e0089,-1,Y,2,C,834,M_ID_29ec8d2ab8,-9,-0.401448,2017-05-08 16:27:11,NaN,-1,27
9671,Y,C_ID_3df86e0089,-1,Y,1,B,367,M_ID_b8a92ea325,-7,-0.661527,2017-07-23 14:12:08,NaN,-1,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29111665,Y,C_ID_92039ab1ac,-1,Y,1,B,879,M_ID_9139332ccc,-5,-0.489804,2017-07-26 09:41:45,NaN,-1,29
29111666,N,C_ID_92039ab1ac,-1,Y,1,B,879,M_ID_9139332ccc,-4,-0.587927,2017-08-09 15:45:58,NaN,-1,29
29111698,Y,C_ID_4efb62f6b5,-1,Y,1,B,879,M_ID_9139332ccc,-2,-0.743918,2017-12-13 19:14:59,NaN,-1,29
29111700,Y,C_ID_97aaf28100,-1,Y,2,C,879,M_ID_00a6ca8a8a,-2,-0.476431,2017-12-12 19:37:13,NaN,-1,29
29111704,N,C_ID_f8596d4a71,-1,Y,1,B,734,M_ID_51edbd1782,-9,-0.626696,2017-05-02 20:47:28,NaN,-1,25
29111705,Y,C_ID_f8596d4a71,-1,Y,1,B,755,M_ID_86be58d7e0,-6,-0.686952,2017-08-10 17:10:16,NaN,-1,8
29111706,Y,C_ID_f8596d4a71,-1,Y,1,B,755,M_ID_86be58d7e0,-3,-0.686817,2017-11-05 08:19:29,NaN,-1,8
29111707,Y,C_ID_f8596d4a71,-1,Y,1,B,755,M_ID_86be58d7e0,0,-0.686817,2018-02-05 08:02:07,NaN,-1,8

In [18]:
history.groupby('card_id').category_1.unique()

card_id
C_ID_00007093c1    [N, Y]
C_ID_0001238066    [N, Y]
C_ID_0001506ef0       [N]
C_ID_0001793786    [N, Y]
C_ID_000183fdda    [N, Y]
C_ID_00024e244b       [N]
C_ID_0002709b5a    [N, Y]
C_ID_00027503e2       [N]
C_ID_000298032a       [N]
C_ID_0002ba3c2e       [N]
C_ID_0002c7c2c1       [N]
C_ID_00032df08f    [N, Y]
C_ID_0003754056       [N]
C_ID_000377f6a0       [N]
C_ID_0003be3c83    [N, Y]
C_ID_0003f41435       [N]
C_ID_00042d509c    [Y, N]
C_ID_0004587331    [N, Y]
C_ID_0004725b87       [N]
C_ID_0004888ddd    [N, Y]
C_ID_0004b68c49    [Y, N]
C_ID_0004c2a5ab    [Y, N]
C_ID_00057b99fe       [N]
C_ID_000599daf9       [N]
C_ID_0005b2f279       [N]
C_ID_0005b5804f       [N]
C_ID_0005f16cc8    [N, Y]
C_ID_0006152db8    [N, Y]
C_ID_000616f4a8    [N, Y]
C_ID_000664aa02       [N]
C_ID_00079fec55    [Y, N]
C_ID_0007a60a33       [N]
C_ID_0007fe3157    [N, Y]
C_ID_000844d8f1       [N]
C_ID_0008461020    [N, Y]
C_ID_00087f3079       [N]
C_ID_0009010641    [Y, N]
C_ID_0009150c11       [N]
C_ID_000950bc78    [N, Y]
C_ID_00099cb909       [N]
C_ID_0009ae74c1    [N, Y]
C_ID_0009d25138    [N, Y]
C_ID_0009ef1dc2       [N]
C_ID_000a6044e9    [N, Y]
C_ID_000a9864df    [N, Y]
C_ID_000aa2220e    [N, Y]
C_ID_000acab1f6    [N, Y]
C_ID_000b0305d9    [N, Y]
C_ID_000b13135b    [N, Y]
C_ID_000b24f797    [N, Y]
C_ID_000b3dbdea       [N]
C_ID_000b503737    [N, Y]
C_ID_000b72c028    [N, Y]
C_ID_000c00fc96       [N]
C_ID_000c1a998b    [N, Y]
C_ID_000c778b05       [N]
C_ID_000c8010ac    [Y, N]
C_ID_000cadb0f6    [Y, N]
C_ID_000cadb59e    [N, Y]
C_ID_000ce910cb    [Y, N]
C_ID_000cfb6503       [N]
C_ID_000d005e43       [N]
C_ID_000d0a81c5    [N, Y]
C_ID_000d22fabd       [N]
C_ID_000dd1a097       [N]
C_ID_000dd8c722       [N]
C_ID_000dfced4d       [N]
C_ID_000e0c94f7    [N, Y]
C_ID_000e19e469       [N]
C_ID_000e518263    [Y, N]
C_ID_000edf11d7       [N]
C_ID_000ee9a514    [N, Y]
C_ID_000ef9e20b       [N]
C_ID_000f023e16       [N]
C_ID_000f2de962    [N, Y]
C_ID_000f4ebb37       [N]
C_ID_000f6fea6a    [N, Y]
C_ID_000f76201e    [Y, N]
C_ID_000f7b7753       [N]
C_ID_000f7e3e49    [Y, N]
C_ID_000fbd9928       [N]
C_ID_000fc266be       [N]
C_ID_000fd44a39    [N, Y]
C_ID_0010376f50       [N]
C_ID_0010779aaf    [Y, N]
C_ID_0011057de1    [N, Y]
C_ID_0011762232       [N]
C_ID_00117c1aeb       [N]
C_ID_00117f101b       [N]
C_ID_00119bb665       [N]
C_ID_0011a89fcc    [N, Y]
C_ID_0011c836e7       [N]
C_ID_0011e63c0d       [N]
C_ID_0011ee467f    [Y, N]
C_ID_00122c3b8d    [N, Y]
C_ID_00127204f5       [N]
C_ID_001272c2c6    [N, Y]
C_ID_00128a24cf       [N]
C_ID_0012bcf581       [N]
C_ID_00130ac58d       [N]
C_ID_00136926d8       [N]
C_ID_0013f936f0       [N]
C_ID_001454b74c    [N, Y]
C_ID_001482362b    [N, Y]
C_ID_00149a71a4       [N]
C_ID_00151200a5       [N]
C_ID_0015677437       [N]
C_ID_0015cb7ed9    [N, Y]
C_ID_0015e02e4c       [N]
C_ID_0015f549cb       [N]
C_ID_0016563f06    [N, Y]
C_ID_00165af96d       [N]
C_ID_001676af4f    [Y, N]
C_ID_00167ca6d8       [N]
C_ID_00169b9828       [N]
C_ID_0016b189b4    [N, Y]
C_ID_0016e257a5    [N, Y]
C_ID_0016eb652c       [N]
C_ID_0017c2ec57       [N]
C_ID_0017dadfd5    [N, Y]
C_ID_0017fee682    [N, Y]
C_ID_00186a15ce       [N]
C_ID_00187526cf    [N, Y]
C_ID_0018bfbe9d    [N, Y]
C_ID_00191957a1    [N, Y]
C_ID_00192a74ce    [N, Y]
C_ID_00196c38d5    [N, Y]
C_ID_001982552a    [N, Y]
C_ID_001a1de282       [N]
C_ID_001aa75740    [Y, N]
C_ID_001acb9182       [N]
C_ID_001addb9d7    [N, Y]
C_ID_001ae38fdf    [N, Y]
C_ID_001b3f2dd2       [N]
C_ID_001b43d48f    [N, Y]
C_ID_001b4c5151    [Y, N]
C_ID_001b68a34b    [N, Y]
C_ID_001b81c304    [N, Y]
C_ID_001b853b44       [N]
C_ID_001b9c4a97    [N, Y]
C_ID_001bd2c99c       [N]
C_ID_001bd54f5e    [N, Y]
C_ID_001bdd0f69       [N]
C_ID_001c09a36b       [Y]
C_ID_001c1581a8       [N]
C_ID_001cb1aa86       [N]
C_ID_001cbc2343    [N, Y]
C_ID_001d401a8c       [N]
C_ID_001d7f9262       [N]
C_ID_001da949e5       [N]
C_ID_001db316bf    [Y, N]
C_ID_001de6764b    [Y, N]
C_ID_001e0c63c7    [N, Y]
C_ID_001e2bb2ce       [N]
C_ID_001e4e94e5       [N]
C_ID_001f019c09       [N]
C_ID_001f2d7b8c    [N, Y]
C_ID_001fb79a42       [N]
C_ID_001fc7b4d5    [N, Y]
C_ID_001fd0fe89       [N]
C_ID_00201d9bd1       [N]
C_ID_00201eee66    [N, Y]
C_ID_0020246399       [N]
C_ID_0020e01cf5    [N, Y]
C_ID_0020f8197d       [N]
C_ID_00210d1bff       [N]
C_ID_00216bdb6a       [N]
C_ID_002198cdf1       [N]
C_ID_0021ea1fb7       [N]
C_ID_002249e66d    [N, Y]
C_ID_002263a16a    [N, Y]
C_ID_0022ce1648    [N, Y]
C_ID_0022d08784       [N]
C_ID_002315a188       [N]
C_ID_002315dc90    [N, Y]
C_ID_00232be11f       [N]
C_ID_0023e2c382    [Y, N]
C_ID_0023faafd2       [N]
C_ID_0024770552       [N]
C_ID_0024aaee36       [N]
C_ID_0024e3b7d7       [N]
C_ID_0024ec2d9c       [N]
C_ID_00251f994c    [Y, N]
C_ID_00254bc137       [N]
C_ID_0025a6dbe7    [N, Y]
C_ID_0026850f57       [N]
C_ID_002776e95a    [N, Y]
C_ID_002780b4cf    [N, Y]
C_ID_0027d7e25e       [N]
C_ID_00286850f5    [N, Y]
C_ID_002887180d       [N]
C_ID_0028ac8028       [N]
C_ID_0028c1608e       [N]
C_ID_0028e15a78       [Y]
C_ID_00290b8994    [N, Y]
C_ID_002936ada6    [N, Y]
C_ID_0029435cf6       [N]
C_ID_00298b7d14       [N]
C_ID_0029d52418    [Y, N]
C_ID_0029ede787       [N]
                    ...
C_ID_ffdc5009c1       [N]
C_ID_ffdc82f906       [N]
C_ID_ffdca28518    [N, Y]
C_ID_ffdcc94d1f       [N]
C_ID_ffdcd19708    [N, Y]
C_ID_ffdcdfc623       [N]
C_ID_ffdd77f2de    [Y, N]
C_ID_ffddd6feb9    [N, Y]
C_ID_ffddfebbf5       [N]
C_ID_ffde58aa74    [N, Y]
C_ID_ffdee57646       [N]
C_ID_ffdf22a70e       [N]
C_ID_ffdf5b6f63       [N]
C_ID_ffdf5e0a5d       [N]
C_ID_ffdf8608e4       [N]
C_ID_ffdf9871b8       [N]
C_ID_ffdf9cd58e       [N]
C_ID_ffdfb5f8e3    [Y, N]
C_ID_ffdfb75892       [N]
C_ID_ffdfdf7264    [Y, N]
C_ID_ffdfffc597       [N]
C_ID_ffe0195528       [N]
C_ID_ffe0232b20       [N]
C_ID_ffe044a946    [N, Y]
C_ID_ffe04f03a1    [Y, N]
C_ID_ffe060b506    [Y, N]
C_ID_ffe072a280    [Y, N]
C_ID_ffe088e166       [N]
C_ID_ffe08ab076       [N]
C_ID_ffe0be1342    [N, Y]
C_ID_ffe0d0ddb9       [N]
C_ID_ffe0fbaecd       [N]
C_ID_ffe1192b9d    [Y, N]
C_ID_ffe15e812b    [Y, N]
C_ID_ffe16cfd99       [N]
C_ID_ffe1a60d1c       [N]
C_ID_ffe1bf3c5a    [N, Y]
C_ID_ffe21478f1       [N]
C_ID_ffe214bc43       [N]
C_ID_ffe216e5a1       [N]
C_ID_ffe2a5b3f9       [N]
C_ID_ffe2a75820       [N]
C_ID_ffe2e4af9c       [N]
C_ID_ffe308727f    [N, Y]
C_ID_ffe3107dae       [N]
C_ID_ffe37f9923    [N, Y]
C_ID_ffe390749d       [Y]
C_ID_ffe39f6c88       [N]
C_ID_ffe3bdc3d6       [N]
C_ID_ffe4eb895f       [N]
C_ID_ffe513f669    [N, Y]
C_ID_ffe545e848    [N, Y]
C_ID_ffe56e0c89    [N, Y]
C_ID_ffe5cb03ac    [N, Y]
C_ID_ffe609698f       [N]
C_ID_ffe670105f       [N]
C_ID_ffe688fd68    [Y, N]
C_ID_ffe6a84c59    [Y, N]
C_ID_ffe6dcc805       [N]
C_ID_ffe703f745    [N, Y]
C_ID_ffe71ec373       [N]
C_ID_ffe754d10c       [N]
C_ID_ffe7871f38       [N]
C_ID_ffe791f795       [N]
C_ID_ffe7a0256d       [N]
C_ID_ffe80c5734       [N]
C_ID_ffe83ac1ec       [N]
C_ID_ffe85078c8    [N, Y]
C_ID_ffe8541af1    [N, Y]
C_ID_ffe85833bd    [N, Y]
C_ID_ffe8645e27    [N, Y]
C_ID_ffe8bf9ef2    [N, Y]
C_ID_ffe8e34523       [N]
C_ID_ffe9091205    [N, Y]
C_ID_ffe9338443       [N]
C_ID_ffe969e56f    [N, Y]
C_ID_ffe97acefc    [N, Y]
C_ID_ffe98a4674    [N, Y]
C_ID_ffe9944d60       [N]
C_ID_ffea783298       [N]
C_ID_ffea95ca66       [N]
C_ID_ffeaa35463    [Y, N]
C_ID_ffeacaa081       [N]
C_ID_ffeb02d2bb       [N]
C_ID_ffeb0898b5    [Y, N]
C_ID_ffeb258d93       [N]
C_ID_ffeb978d3b    [N, Y]
C_ID_ffebe44c6d    [N, Y]
C_ID_ffebf84f15       [Y]
C_ID_ffec0ead94       [N]
C_ID_ffec3e797c    [N, Y]
C_ID_ffec483ae9    [Y, N]
C_ID_ffec615a26       [N]
C_ID_ffec69c581       [N]
C_ID_ffec7d3b3b       [N]
C_ID_ffec95782a       [N]
C_ID_ffecac6ec9       [N]
C_ID_ffecc9625f    [N, Y]
C_ID_ffeccd43c9       [N]
C_ID_ffece651ab       [N]
C_ID_ffed5c1f3e       [N]
C_ID_ffedb3bbdb    [N, Y]
C_ID_ffee45f941       [N]
C_ID_ffeec704aa    [N, Y]
C_ID_ffeec72833       [N]
C_ID_ffef6a5157    [N, Y]
C_ID_ffef724ee2    [Y, N]
C_ID_ffefdb10d6       [N]
C_ID_ffefee0a04    [N, Y]
C_ID_fff01c7ee1    [Y, N]
C_ID_fff04976bb       [N]
C_ID_fff04aa1f5       [N]
C_ID_fff0688a04    [Y, N]
C_ID_fff06f2aad       [N]
C_ID_fff0ec3a73       [N]
C_ID_fff0f2f9ce    [N, Y]
C_ID_fff115ef2e       [N]
C_ID_fff12bcae2       [N]
C_ID_fff13e9843    [Y, N]
C_ID_fff172a7fa    [Y, N]
C_ID_fff174b839       [N]
C_ID_fff17acd27       [N]
C_ID_fff184faf3       [N]
C_ID_fff1d3ae5f       [N]
C_ID_fff201065c       [N]
C_ID_fff21f3bbc    [N, Y]
C_ID_fff2946cca       [N]
C_ID_fff2ef437b       [N]
C_ID_fff33122b1       [N]
C_ID_fff34656e5       [N]
C_ID_fff38f8134    [N, Y]
C_ID_fff3b3d49e    [N, Y]
C_ID_fff3b465e4    [N, Y]
C_ID_fff3bcdb73    [N, Y]
C_ID_fff3c52f3c       [N]
C_ID_fff47dea33    [N, Y]
C_ID_fff4c4312c    [Y, N]
C_ID_fff4ec311a       [N]
C_ID_fff4ed08c5    [N, Y]
C_ID_fff50bff5e       [N]
C_ID_fff50ce0e0    [N, Y]
C_ID_fff56b7768       [N]
C_ID_fff5be9c03       [N]
C_ID_fff6341ea6    [Y, N]
C_ID_fff678cf7b    [N, Y]
C_ID_fff690bccc       [N]
C_ID_fff6974041       [N]
C_ID_fff6b4456b    [N, Y]
C_ID_fff6bf5305       [N]
C_ID_fff6e4fefb    [N, Y]
C_ID_fff7031631    [N, Y]
C_ID_fff74c6e55    [Y, N]
C_ID_fff7714bc3    [Y, N]
C_ID_fff796a3f9       [N]
C_ID_fff82c2722       [N]
C_ID_fff845b82f       [N]
C_ID_fff8874bc1    [N, Y]
C_ID_fff8d507b4       [N]
C_ID_fff8e0d7da       [N]
C_ID_fff91cdd28    [N, Y]
C_ID_fff96876e0       [N]
C_ID_fff9e6b8e4       [N]
C_ID_fffa2280c9    [N, Y]
C_ID_fffa2ced7d       [N]
C_ID_fffa362304       [Y]
C_ID_fffa99d1da    [N, Y]
C_ID_fffadd3551    [Y, N]
C_ID_fffaed41f0       [N]
C_ID_fffb59b27a       [Y]
C_ID_fffb67f260       [N]
C_ID_fffb79fb56       [N]
C_ID_fffb9ea3f6    [N, Y]
C_ID_fffba72dc5       [N]
C_ID_fffbdf036b       [N]
C_ID_fffbee5c24       [N]
C_ID_fffc96bf24    [N, Y]
C_ID_fffcb74f49    [N, Y]
C_ID_fffcf66e12       [N]
C_ID_fffd070e0e       [N]
C_ID_fffd1207a8       [N]
C_ID_fffd24dcf3    [N, Y]
C_ID_fffd337484    [N, Y]
C_ID_fffd345048       [N]
C_ID_fffd351e7f    [N, Y]
C_ID_fffd93c8bf       [N]
C_ID_fffd943b91    [N, Y]
C_ID_fffdad8aa0       [N]
C_ID_fffde15ab6    [N, Y]
C_ID_fffdf34798       [N]
C_ID_fffe29a04a       [N]
C_ID_fffe78b232    [N, Y]
C_ID_fffe866457       [N]
C_ID_fffea6de74    [N, Y]
C_ID_fffeced303    [Y, N]
C_ID_fffeed3a89    [N, Y]
C_ID_ffff1d9928    [N, Y]
C_ID_ffff579d3a       [N]
C_ID_ffff756266    [N, Y]
C_ID_ffff828181    [N, Y]
C_ID_fffffd5772    [Y, N]
Name: category_1, Length: 325540, dtype: object

In [26]:
history.city_id.value_counts(dropna=False)

 69     4835441
-1      2478624
 19     1151077
 158    1113013
 17      971714
 331     714414
 143     668769
 88      659328
 137     603023
 333     561144
 87      444940
 212     406196
 57      382232
 149     359540
 25      356757
 233     355108
 117     322414
 160     317617
 213     248371
 277     247294
 286     231877
 76      216048
 4       212403
 107     210182
 53      209668
 20      207650
 291     199983
 140     190359
 344     177694
 161     168745
 51      164222
 283     163347
 322     153926
 21      149278
 246     139898
 179     138888
 200     137668
 231     137245
 244     133140
 138     132244
 169     132161
 289     131576
 116     128194
 340     124669
 60      118852
 251     118368
 248     117916
 96      110001
 1       108519
 274     106563
 302     106447
 199     101660
 314      99370
 12       96647
 11       92785
 8        89353
 30       83598
 110      83196
 279      79094
 90       77047
 24       74184
 42       72730
 334      70606
 33       67797
 159      66568
 320      65485
 14       64610
 64       63373
 280      62054
 188      61846
 48       60639
 288      60347
 210      60119
 278      59949
 173      59400
 147      58555
 131      58055
 339      56509
 271      56498
 126      56107
 168      55587
 276      55257
 34       55131
 189      53926
 171      53067
 109      51310
 297      50198
 247      50058
 78       49755
 102      49716
 300      48781
 292      48490
 174      47294
 268      46863
 242      46777
 282      46600
 232      46396
 56       45031
 155      44379
 238      44245
 250      44014
 296      43958
 347      43617
 52       43539
 181      43034
 3        42665
 209      42602
 308      42460
 272      41248
 135      40805
 219      39866
 36       39374
 253      39269
 136      38474
 323      37486
 66       37484
 226      37217
 211      37213
 125      36500
 157      36153
 259      35703
 245      35595
 79       35580
 329      35343
 41       35269
 330      34942
 97       34579
 162      34238
 29       34057
 261      33605
 10       33395
 13       32701
 234      32691
 256      32253
 170      31750
 341      31500
 62       31310
 156      31019
 218      30841
 124      30717
 191      30491
 94       30104
 325      29257
 295      28073
 129      28069
 318      27786
 304      27744
 148      27391
 98       27093
 223      26834
 163      26388
 190      25983
 175      25906
 101      25705
 38       24953
 265      24948
 6        24220
 303      24206
 150      24077
 299      24032
 172      23928
 22       23707
 46       23671
 28       23586
 180      23267
 214      23260
 260      23251
 328      22886
 63       22705
 165      22645
 281      22636
 105      22582
 187      22541
 7        22477
 23       22236
 123      22115
 193      21699
 301      21367
 9        21053
 270      20984
 186      20898
 119      20846
 111      20666
 229      20642
 311      20513
 115      20461
 82       20458
 195      20391
 167      20387
 100      20313
 216      20003
 145      19852
 255      19653
 146      19296
 275      18958
 75       18752
 239      18711
 91       18663
 337      18568
 128      18459
 266      18330
 153      18263
 182      18191
 201      17918
 74       17841
 194      17838
 220      17813
 342      17622
 197      17456
 183      17431
 198      17335
 166      17292
 2        17171
 58       17124
 184      16977
 313      16710
 68       16562
 70       16500
 203      16424
 49       16300
 230      16250
 312      15860
 294      15828
 83       15762
 120      15655
 144      15622
 139      15579
 267      15384
 290      15307
 310      15240
 85       15153
 73       15084
 307      14958
 47       14893
 208      14803
 338      14757
 39       14481
 309      14435
 106      14349
 44       13862
 252      13617
 262      13005
 80       12786
 206      12764
 108      12732
 264      12595
 104      12590
 335      12474
 287      12197
 142      12139
 114      12126
 343      12113
 240      12018
 269      11918
 228      11857
 16       11747
 224      11685
 285      11654
 236      11264
 258      11056
 40       10959
 298      10661
 345      10424
 103      10170
 35       10128
 113      10084
 151       9986
 133       9872
 26        9845
 321       9808
 77        9736
 18        9565
 61        9458
 86        9372
 65        9352
 336       9022
 222       8819
 118       8518
 32        8382
 81        8278
 54        8201
 235       7918
 326       7912
 293       7804
 327       7499
 112       7461
 84        7367
 237       7285
 227       7233
 254       7143
 71        6781
 204       6745
 306       6128
 221       6096
 130       5657
 122       5458
 205       5385
 215       4791
 89        4760
 178       4430
 263       4003
 207       3905
 315       3845
 319       1645
 92         758
 273        620
 316        149
 185         45
Name: city_id, dtype: int64

In [28]:
history[history.city_id.isnull()]

Empty DataFrame
Columns: [authorized_flag, card_id, city_id, category_1, installments, category_3, merchant_category_id, merchant_id, month_lag, purchase_amount, purchase_date, category_2, state_id, subsector_id]
Index: []

In [34]:
history['purchase_amount_new'] = np.round(history['purchase_amount'] / 0.00150265118 + 497.06,2)

In [36]:
history[history.card_id == 'C_ID_00007093c1'].sort_values('purchase_date')[['authorized_flag', 'city_id', 'category_1', 'merchant_category_id', 'merchant_id', 'purchase_amount_new', 'purchase_date']]

,authorized_flag,city_id,category_1,merchant_category_id,merchant_id,purchase_amount_new,purchase_date
19095896,Y,244,N,705,M_ID_69423b34e4,521.80,2017-02-14 14:00:43
19095775,Y,244,N,705,M_ID_a33355a1b7,186.00,2017-02-14 15:47:45
19095845,Y,244,N,307,M_ID_9400cf2342,116.00,2017-02-16 15:37:58
19095866,Y,244,N,705,M_ID_a33355a1b7,276.40,2017-02-20 12:19:01
19095808,Y,244,N,307,M_ID_9400cf2342,175.00,2017-03-03 00:24:15
19095905,Y,244,N,307,M_ID_9400cf2342,116.00,2017-03-06 18:50:42
19095780,Y,244,N,705,M_ID_69423b34e4,230.00,2017-03-08 15:05:29
19095816,Y,244,N,307,M_ID_9400cf2342,60.00,2017-03-08 16:12:35
19095833,Y,244,N,705,M_ID_69423b34e4,120.00,2017-03-11 15:04:31
19095922,Y,244,N,705,M_ID_69423b34e4,45.90,2017-03-11 15:10:15
19095885,Y,244,N,705,M_ID_69423b34e4,120.00,2017-03-11 15:26:58
19095855,N,244,N,307,M_ID_9400cf2342,126.00,2017-03-11 16:28:46
19095882,N,244,N,307,M_ID_9400cf2342,126.00,2017-03-11 16:29:20
19095837,N,244,N,307,M_ID_9400cf2342,50.00,2017-03-15 17:13:38
19095900,Y,244,N,705,M_ID_bc3f2e986e,36.50,2017-04-17 19:19:54
19095787,Y,244,N,705,M_ID_bc3f2e986e,52.30,2017-04-17 19:22:18
19095910,Y,244,N,307,M_ID_9400cf2342,112.00,2017-04-17 19:37:08
19095862,Y,-1,Y,755,M_ID_57df19bf28,12.00,2017-04-17 20:20:37
19095805,Y,-1,Y,755,M_ID_57df19bf28,12.00,2017-04-17 20:29:12
19095781,Y,244,N,307,M_ID_9400cf2342,60.00,2017-04-17 21:31:17
19095891,Y,244,N,705,M_ID_69423b34e4,500.00,2017-04-19 11:46:58
19095841,Y,244,N,705,M_ID_69423b34e4,218.45,2017-04-19 12:19:08
19095858,N,244,N,705,M_ID_8261f7a734,290.00,2017-04-19 12:34:46
19095873,Y,244,N,705,M_ID_8261f7a734,200.00,2017-04-19 12:35:45
19095815,N,244,N,705,M_ID_8261f7a734,90.00,2017-04-19 12:36:29
19095884,N,244,N,705,M_ID_8261f7a734,50.00,2017-04-19 12:36:49
19095875,N,244,N,307,M_ID_9400cf2342,100.13,2017-05-11 18:56:46
19095898,Y,244,N,307,M_ID_9400cf2342,82.00,2017-05-15 14:50:52
19095908,Y,244,N,367,M_ID_109e9d2b1d,106.00,2017-05-16 17:16:11
19095776,N,244,N,108,M_ID_15446e939c,702.00,2017-05-18 16:52:22
19095794,N,244,N,108,M_ID_15446e939c,702.00,2017-05-18 16:53:21
19095889,N,244,N,108,M_ID_15446e939c,500.00,2017-05-18 16:53:49
19095907,Y,244,N,108,M_ID_15446e939c,300.00,2017-05-18 16:54:17
19095890,Y,244,N,307,M_ID_9400cf2342,32.00,2017-05-22 16:12:35
19095872,Y,244,N,307,M_ID_9400cf2342,57.00,2017-05-29 14:44:58
19095842,Y,244,N,607,M_ID_3c6556f2dd,110.00,2017-05-30 11:10:06
19095886,Y,244,N,705,M_ID_69423b34e4,120.55,2017-06-01 18:42:38
19095916,Y,244,N,307,M_ID_9400cf2342,42.02,2017-06-01 19:30:29
19095906,Y,244,N,307,M_ID_9400cf2342,80.00,2017-06-06 21:01:12
19095871,Y,244,N,45,M_ID_0379adb435,56.00,2017-06-07 10:28:34
19095881,Y,244,N,298,M_ID_0dabc5a70c,98.00,2017-06-07 10:47:20
19095892,Y,244,N,307,M_ID_9400cf2342,196.00,2017-06-07 17:15:05
19095851,Y,244,N,427,M_ID_24e067cb2b,341.00,2017-06-09 10:47:39
19095793,Y,76,N,422,M_ID_a614b6d5b0,30.00,2017-06-10 11:06:51
19095883,N,-1,Y,755,M_ID_57df19bf28,12.00,2017-06-14 14:18:48
19095874,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-06-14 14:22:05
19095880,Y,244,N,307,M_ID_9400cf2342,49.00,2017-06-14 18:14:15
19095783,N,244,N,222,M_ID_ee8fcd02ca,500.00,2017-06-17 10:53:40
19095899,N,244,N,222,M_ID_ee8fcd02ca,400.00,2017-06-17 10:54:08
19095822,N,244,N,222,M_ID_ee8fcd02ca,300.00,2017-06-17 10:54:36
19095829,Y,244,N,222,M_ID_ee8fcd02ca,200.00,2017-06-17 10:55:05
19095788,N,244,N,307,M_ID_9400cf2342,85.00,2017-06-23 13:17:47
19095856,Y,244,N,705,M_ID_a33355a1b7,120.00,2017-06-29 16:10:08
19095914,N,244,N,307,M_ID_9400cf2342,115.03,2017-06-29 16:52:18
19095854,Y,244,N,307,M_ID_9400cf2342,115.03,2017-06-29 16:52:47
19095807,Y,76,N,307,M_ID_f5668a871f,20.00,2017-07-02 08:23:52
19095795,Y,76,N,705,M_ID_d96a11b2df,113.19,2017-07-02 09:01:40
19095778,Y,-1,Y,755,M_ID_57df19bf28,25.00,2017-07-03 15:43:57
19095895,Y,244,N,705,M_ID_69423b34e4,121.60,2017-07-04 17:14:03
19095852,Y,244,N,705,M_ID_bc3f2e986e,236.00,2017-07-04 17:33:17
19095799,Y,244,N,367,M_ID_109e9d2b1d,39.00,2017-07-05 17:27:26
19095796,Y,76,N,683,M_ID_6a1f75f661,220.00,2017-07-05 17:57:21
19095888,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-07-06 10:58:03
19095846,Y,244,N,45,M_ID_0379adb435,151.00,2017-07-06 12:41:24
19095836,Y,244,N,307,M_ID_9400cf2342,40.00,2017-07-08 11:58:06
19095797,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-07-14 11:51:05
19095801,N,244,N,307,M_ID_9400cf2342,91.00,2017-07-18 13:48:46
19095894,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-07-31 16:01:04
19095869,N,244,N,307,M_ID_9400cf2342,100.00,2017-07-31 21:30:24
19095876,Y,244,N,307,M_ID_9400cf2342,100.00,2017-07-31 21:31:36
19095912,N,-1,Y,755,M_ID_57df19bf28,25.00,2017-08-01 07:13:59
19095839,Y,-1,Y,755,M_ID_57df19bf28,25.00,2017-08-01 07:16:57
19095819,Y,244,N,307,M_ID_9400cf2342,100.00,2017-08-04 15:40:55
19095834,Y,76,N,206,M_ID_584ad6cd63,460.00,2017-08-05 10:23:37
19095777,Y,76,N,45,M_ID_84e60960a3,125.00,2017-08-05 11:27:35
19095897,Y,76,N,705,M_ID_d96a11b2df,100.00,2017-08-06 07:49:23
19095790,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-08-07 17:46:13
19095840,Y,244,N,45,M_ID_0379adb435,65.00,2017-08-08 15:26:32
19095838,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-08-14 12:11:26
19095830,Y,244,N,307,M_ID_9400cf2342,100.00,2017-08-14 16:51:19
19095913,Y,244,N,307,M_ID_9400cf2342,126.00,2017-08-18 14:09:09
19095826,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-08-22 09:17:57
19095893,Y,76,N,683,M_ID_6a1f75f661,70.00,2017-08-26 09:51:16
19095863,N,244,N,373,M_ID_490fc654fb,1500.00,2017-08-28 11:43:28
19095791,Y,244,N,373,M_ID_490fc654fb,1300.00,2017-08-28 11:44:16
19095847,N,244,N,373,M_ID_490fc654fb,100.00,2017-08-28 11:46:28
19095843,Y,244,N,307,M_ID_9400cf2342,42.00,2017-08-28 19:21:16
19095809,Y,-1,Y,755,M_ID_57df19bf28,25.00,2017-09-04 15:07:02
19095887,N,-1,Y,755,M_ID_57df19bf28,17.00,2017-09-08 13:24:49
19095818,Y,244,N,45,M_ID_0379adb435,220.00,2017-09-25 12:14:35
19095850,Y,244,N,307,M_ID_9400cf2342,113.07,2017-09-25 20:07:44
19095911,Y,244,N,298,M_ID_0dabc5a70c,149.50,2017-09-28 14:39:39
19095810,Y,-1,Y,755,M_ID_57df19bf28,25.00,2017-10-01 08:05:54
19095825,Y,-1,Y,755,M_ID_57df19bf28,25.00,2017-10-02 12:40:58
19095803,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-10-02 15:37:23
19095921,Y,244,N,705,M_ID_8261f7a734,107.00,2017-10-02 17:41:36
19095774,Y,244,N,307,M_ID_9400cf2342,144.00,2017-10-02 19:09:42
19095798,N,244,N,45,M_ID_58fa2d2ab7,140.00,2017-10-05 21:22:06
19095804,Y,244,N,307,M_ID_9400cf2342,64.78,2017-10-05 21:55:06
19095919,Y,244,N,307,M_ID_5357547c3e,154.00,2017-10-06 21:40:23
19095901,N,244,N,705,M_ID_8261f7a734,153.00,2017-10-09 15:53:29
19095878,N,244,N,705,M_ID_8261f7a734,153.00,2017-10-09 15:54:04
19095879,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-10-19 14:20:38
19095824,N,244,N,307,M_ID_9400cf2342,65.02,2017-10-23 22:47:52
19095828,Y,244,N,68,M_ID_61f1337e5d,55.00,2017-10-26 21:04:26
19095867,Y,244,N,126,M_ID_f6d28ce95b,79.90,2017-10-26 21:19:15
19095817,N,-1,Y,755,M_ID_57df19bf28,49.89,2017-10-28 16:13:10
19095904,Y,76,N,683,M_ID_6a1f75f661,149.00,2017-10-28 19:42:29
19095849,Y,244,N,307,M_ID_5357547c3e,115.00,2017-10-28 20:11:04
19095835,Y,-1,Y,755,M_ID_57df19bf28,25.00,2017-11-01 07:05:09
19095831,Y,333,N,307,M_ID_1b440d74fb,236.00,2017-11-03 19:24:09
19095813,Y,76,N,45,M_ID_84e60960a3,527.00,2017-11-09 16:20:00
19095802,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-11-10 15:34:30
19095827,N,76,N,705,M_ID_edeafa75d9,118.25,2017-11-10 16:21:22
19095820,Y,-1,Y,755,M_ID_57df19bf28,17.00,2017-11-20 17:27:59
19095864,Y,-1,Y,755,M_ID_57df19bf28,25.00,2017-12-01 05:06:36
19095821,Y,244,N,222,M_ID_ee8fcd02ca,220.00,2017-12-01 11:02:37
19095789,Y,244,N,307,M_ID_9400cf2342,123.11,2017-12-01 19:24:28
19095784,Y,244,N,222,M_ID_ee8fcd02ca,300.00,2017-12-04 18:03:51
19095868,Y,244,N,222,M_ID_ee8fcd02ca,262.00,2017-12-07 17:48:54
19095915,N,244,N,705,M_ID_69423b34e4,400.00,2017-12-09 11:34:09
19095814,Y,244,N,307,M_ID_9400cf2342,70.03,2017-12-09 13:59:34
19095918,Y,244,N,307,M_ID_9400cf2342,30.05,2017-12-13 20:07:17
19095909,Y,244,N,307,M_ID_9400cf2342,50.00,2017-12-13 20:08:05
19095832,Y,244,N,307,M_ID_9400cf2342,129.00,2017-12-28 18:25:55
19095902,Y,244,N,45,M_ID_58fa2d2ab7,290.00,2017-12-30 13:06:45
19095917,Y,244,N,307,M_ID_9400cf2342,86.03,2017-12-30 16:29:38
19095857,Y,-1,Y,755,M_ID_57df19bf28,25.00,2018-01-01 05:07:37
19095779,Y,244,N,307,M_ID_5357547c3e,236.00,2018-01-05 13:55:01
19095782,Y,244,N,705,M_ID_a33355a1b7,218.59,2018-01-08 16:15:07
19095860,Y,244,N,705,M_ID_69423b34e4,200.00,2018-01-08 16:58:13
19095848,Y,244,N,45,M_ID_2efbd71a00,52.00,2018-01-08 18:13:40
19095920,N,244,N,307,M_ID_9400cf2342,150.00,2018-01-08 18:58:43
19095823,N,244,N,307,M_ID_9400cf2342,100.00,2018-01-08 18:59:09
19095853,Y,244,N,307,M_ID_9400cf2342,50.00,2018-01-08 18:59:38
19095812,Y,-1,Y,755,M_ID_57df19bf28,25.00,2018-01-30 05:06:15
19095806,Y,244,N,307,M_ID_9400cf2342,130.00,2018-01-30 19:27:40
19095861,Y,244,N,307,M_ID_5357547c3e,144.33,2018-02-02 18:28:53
19095785,Y,-1,Y,755,M_ID_57df19bf28,17.00,2018-02-05 08:56:11
19095844,Y,76,N,45,M_ID_84e60960a3,500.00,2018-02-06 15:34:09
19095865,Y,76,N,818,M_ID_c6ca6282e6,82.00,2018-02-07 07:34:15
19095792,N,76,N,206,M_ID_584ad6cd63,163.50,2018-02-07 09:50:43
19095800,Y,76,N,206,M_ID_584ad6cd63,163.50,2018-02-07 09:51:03
19095811,Y,76,N,206,M_ID_584ad6cd63,163.50,2018-02-07 09:54:23
19095859,Y,76,N,437,M_ID_06a8d84366,207.44,2018-02-07 11:11:27
19095870,N,76,N,705,M_ID_d96a11b2df,188.91,2018-02-08 16:35:37
19095903,N,76,N,705,M_ID_d96a11b2df,100.00,2018-02-08 16:36:19
19095786,N,76,N,705,M_ID_d96a11b2df,50.00,2018-02-08 16:37:19
19095877,Y,-1,Y,755,M_ID_57df19bf28,25.00,2018-02-27 05:14:57

In [31]:
sorted(history.state_id.value_counts().index)

[-1,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

* category2 > state > city > category1

In [41]:
merchant = pd.read_csv('./data/merchants.csv')

In [79]:
merchant[merchant.merchant_id == 'M_ID_9400cf2342']

,merchant_id,merchant_group_id,merchant_category_id,subsector_id,numerical_1,numerical_2,category_1,most_recent_sales_range,most_recent_purchases_range,avg_sales_lag3,avg_purchases_lag3,active_months_lag3,avg_sales_lag6,avg_purchases_lag6,active_months_lag6,avg_sales_lag12,avg_purchases_lag12,active_months_lag12,category_4,city_id,state_id,category_2
287098,M_ID_9400cf2342,60307,307,19,-0.047556,-0.057471,N,D,D,0.88,0.88017,3,0.96,0.959246,6,1.02,0.99042,12,N,-1,2,3.0

In [77]:
len(merchant.groupby(['city_id','merchant_group_id']).size().index.get_level_values(1))

216163

In [78]:
len(merchant.groupby(['city_id','merchant_group_id']).size().index.get_level_values(1).unique())

109391

In [52]:
merchant.subsector_id.unique().__len__()

41

In [51]:
merchant.groupby(['merchant_category_id','merchant_group_id']).size()

merchant_category_id  merchant_group_id
-1                    35                     1
 2                    18                     1
                      35                   297
                      83                    68
                      144                    1
                      159                    1
                      205                    1
                      299                    2
                      395                    1
                      508                    1
                      560                    1
                      613                    1
                      630                    1
                      845                    1
                      850                    5
                      886                    2
                      896                    2
                      922                    1
                      986                    1
                      1038                   3
                      1108                   2
                      1399                   1
                      1476                   1
                      1483                   2
                      1495                   1
                      1587                   1
                      1682                   1
                      1743                   1
                      1994                   3
                      2173                   1
                      2439                   1
                      2463                   1
                      2824                   3
                      3016                   1
                      3422                   1
                      3424                   1
                      3426                   1
                      3506                   3
                      3648                   1
                      3674                   1
                      3713                   1
                      3720                   4
                      3816                   3
                      3905                   1
                      3949                   1
                      4029                   1
                      4087                   1
                      4123                   1
                      4182                   1
                      4254                   1
                      4324                   1
                      4339                   1
                      4373                   2
                      4427                   1
                      4618                   1
                      4715                   1
                      4993                   5
                      5166                   1
                      5219                   1
                      5259                   1
                      5364                   1
                      5387                   1
                      5430                   1
                      5549                   2
                      5575                   1
                      5809                   3
                      5948                   5
                      6021                   1
                      6039                   3
                      6156                   1
                      6181                   1
                      6305                   1
                      6408                   1
                      6472                   1
                      6628                   1
                      6669                   1
                      6794                   1
                      6874                   1
                      7059                   1
                      7065                   1
                      7206                   2
                      7407                   1
                      7454                   1
                      7575                   1
                      7592                   1
                      7781                   1
                      7817                   4
                      7869                   1
                      8124                  10
                      8378                   2
                      8396                   1
                      8495                   1
                      8602                   4
                      9105                   1
                      9106                   7
                      9333                   4
                      9399                   1
                      9449                   1
                      9460                   1
                      9514                   7
                      9523                   1
                      9751                   1
                      9752                   1
                      9887                   1
                      9982                   5
                      10090                  1
                      10217                  1
                      10283                  5
                      10301                  3
                      10442                  1
                      10476                  1
                      10666                  1
                      10931                  1
                      10954                  1
                      10971                  1
                      11006                  3
                      11041                  1
                      11105                  1
                      11130                  1
                      11321                  1
                      11344                  1
                      11491                  1
                      11843                  1
                      11898                  1
                      12006                  9
                      12121                  2
                      12184                  1
                      12361                  3
                      12433                  1
                      12864                  1
                      12906                  2
                      13060                  2
                      13197                  1
                      13395                  1
                      13665                  1
                      13811                  2
                      13967                  1
                      13994                  1
                      14102                  8
                      14252                  1
                      14274                  3
                      14422                  1
                      14695                  1
                      14777                  1
                      14973                  1
                      15049                  1
                      15141                  1
                      15147                  1
                      15179                  1
                      15323                  4
                      15341                  5
                      15766                  1
                      16012                  1
                      16190                  1
                      16191                  2
                      16210                  1
                      16471                  1
                      16550                  4
                      16994                  1
                      17019                  1
                      17131                  1
                      17135                  1
                      17351                  1
                      17539                  1
                      17546                  1
                      17628                  1
                      17647                  1
                      17700                  1
                      17838                  1
                      17912                  1
                      18015                  1
                      18149                  1
                      18217                  1
                      18293                  2
                      18398                  1
                      18404                  1
                      18435                  1
                      18473                  1
                      18510                  2
                      18897                  2
                      18916                  1
                      19041                  1
                      19330                  1
                      19349                  1
                      19598                  1
                      19644                  1
                      19735                  3
                      19789                  1
                      19792                  1
                      19935                  1
                      20033                  6
                      20171                  1
                      20429                  1
                      20598                  5
                      20736                  1
                      20796                  3
                      20918                  1
                      20940                  1
                      20951                  1
                      21027                  1
                                          ...
 889                  1416                   1
                      2134                   1
                      5746                   1
                      7662                   1
                      9056                   1
                      9471                   1
                      9603                   1
                      11898                  1
                      13224                  1
                      14590                  2
                      15096                  1
                      15335                  1
                      31192                  1
                      36194                  1
                      41197                  1
                      49993                  1
                      62856                  1
                      71221                  1
                      100827                 1
                      106223                 1
 891                  35                   220
                      51                     1
                      98                     1
                      458                    1
                      1270                   2
                      1400                   3
                      1976                   1
                      2035                   2
                      2385                   1
                      2452                   4
                      2531                   1
                      3506                   1
                      3782                   1
                      4128                   1
                      5577                   5
                      5930                   1
                      6255                   1
                      7617                   1
                      7674                   1
                      8331                   1
                      8400                   1
                      9076                   1
                      9112                   1
                      9177                   2
                      9284                   1
                      9524                   4
                      9619                   1
                      10023                  2
                      10101                  1
                      10827                  2
                      10931                  1
                      11687                  1
                      11789                  1
                      11850                  1
                      11988                  1
                      12851                  1
                      12864                  1
                      13256                  1
                      13495                  2
                      13821                  2
                      14259                  1
                      15316                  1
                      15643                  1
                      16014                  1
                      17173                  1
                      17647                  1
                      17704                  2
                      18388                  1
                      19798                  1
                      19909                  1
                      20437                  8
                      20516                  1
                      21460                  1
                      21666                  5
                      22081                  1
                      22672                  4
                      22916                  1
                      23747                  1
                      23901                  1
                      24186                  2
                      25139                  1
                      25376                  4
                      26067                  4
                      26567                  2
                      26792                  1
                      29399                  2
                      29558                  1
                      30007                  6
                      30029                  1
                      30237                  2
                      30308                  1
                      30620                  1
                      31274                  1
                      32224                  3
                      32499                  1
                      32660                  1
                      33027                  1
                      33724                  1
                      33754                  1
                      34106                  2
                      34290                  1
                      34419                  2
                      35103                  1
                      35222                  1
                      35238                  3
                      35399                  1
                      37436                  1
                      37623                  2
                      37828                  1
                      37893                  1
                      38031                  2
                      39077                  7
                      39209                  1
                      39404                  2
                      39592                  1
                      39635                  1
                      41799                  1
                      42504                  1
                      42972                  2
                      43756                  5
                      44542                  1
                      44588                  1
                      46658                  1
                      47922                  1
                      48825                  1
                      49185                  1
                      49696                  3
                      50015                  4
                      50551                  1
                      51045                  1
                      51944                  1
                      51985                  4
                      53843                  1
                      54773                  2
                      54913                  1
                      57626                  1
                      58125                  1
                      58580                  1
                      59490                  3
                      59589                  1
                      59636                  1
                      59986                  1
                      60397                  1
                      60408                  1
                      60985                  1
                      61209                  3
                      61519                  1
                      61901                  1
                      62423                  1
                      63171                  1
                      63740                  2
                      64084                  1
                      64436                  2
                      64871                  1
                      65223                  2
                      65998                  2
                      66230                  2
                      66952                  1
                      68469                  3
                      69481                  1
                      69534                  1
                      69555                  3
                      70587                  1
                      70606                  1
                      70759                  1
                      70771                  1
                      72128                  1
                      72643                  1
                      73288                  1
                      74357                  1
                      77309                  1
                      80359                  2
                      80584                  1
                      80767                  1
                      82098                  1
                      82633                  3
                      83942                  1
                      84023                  1
                      84024                  1
                      85879                  1
                      86652                  1
                      87468                  1
                      89744                  1
                      90899                  1
                      92527                  1
                      93235                  1
                      94611                  1
                      95139                  1
                      95176                  1
                      96806                  1
                      97308                  1
                      99106                  1
                      102874                 1
                      102990                 1
                      105019                 1
                      106784                 1
                      107409                 1
                      110341                 1
                      110950                 1
                      112158                 1
Length: 178544, dtype: int64

In [94]:
len(merchant)

334696